const CLOUD_BASE = "https://images.cockneycards.com/";
const DEFAULT_PRICE = "£3.49";

// CATEGORIES now lives in categories-data.js — shared with prints-data.js
// / shop-prints.html so both catalogues use the same tree (and stay in
// sync when a team or league gets added). Make sure categories-data.js
// is loaded BEFORE this file wherever this file is included.

const CARD_CATALOGUE = {
  "11plus-boy": { title: "11 Plus Boy Card", description: "A brilliant way to say congratulations on passing the 11 Plus! Add his name and school shirt colour to make it extra special.", categories: ["school-cards", "achievements"], preview: "11plus-boy-preview.png", full: "11plus-boy.png" },
  "11plus-girl": { title: "11 Plus Girl Card", description: "A brilliant way to say congratulations on passing the 11 Plus.", categories: ["school-cards", "achievements"], preview: "11plus-girl-preview.png", full: "11plus-girl.png" },
  "11plus-kids": { title: "11 Plus Kids Card", description: "A brilliant way to say congratulations on passing the 11 Plus.", categories: ["school-cards", "achievements"], preview: "11plus-kids-preview.png", full: "11plus-kids.png" },

  "birthday-80sbirthday": { title: "80s Retro Birthday Card", description: "A colourful birthday card.", categories: ["all", "birthdays", "tv-movies"], preview: "80s-birthday-preview.png", full: "80s-birthday.png" },
  "birthday-90sbirthday": { title: "90s Retro Birthday Card", description: "A colourful birthday card.", categories: ["all", "birthdays", "tv-movies"], preview: "90s-birthday-preview.png", full: "90s-birthday.png" },
  "birthday-artsy-girl": { title: "Artsy Girl Card", description: "A colourful birthday card.", categories: ["all", "for-her", "children", "birthdays"], preview: "artsy-girl-preview.png", full: "artsy-girl.png" },
  "birthday-beerboy": { title: "Birthday Beer", description: "A fun birthday card for someone who loves a cold drink or two.", categories: ["all", "for-him", "birthdays"], preview: "birthday-beer-preview.png", full: "birthday-beer.png" },
  "birthday-grandad1": { title: "Grandads Garden", description: "A warm birthday card celebrating time spent with the family.", categories: ["grandad", "birthdays"], preview: "birthday-grandad1-preview.png", full: "birthday-grandad1.png" },
  "birthday-sweetie": { title: "Sweet Birthday", description: "A colourful birthday card.", categories: ["all", "for-her", "birthdays"], preview: "birthday-sweetie-preview.png", full: "birthday-sweetie.png" },
  "birthday-horse-girl": { title: "Racing Lady", description: "A horse racing themed birthday card - perfect for the racing fan in your life.", categories: ["all", "for-her", "horseracing", "birthdays"], preview: "birthday-horse-girl-preview.png", full: "birthday-horse-girl.png" },
  "birthday-horse-boy": { title: "Racing Gent", description: "A horse racing themed birthday card - perfect for the racing fan in your life.", categories: ["all", "for-him", "horseracing", "birthdays"], preview: "birthday-horse-boy-preview.png", full: "birthday-horse-boy.png" },
  "birthday-gymgirl": { title: "Gym Birthday Babe", description: "A colourful birthday card.", categories: ["all", "for-her", "birthdays"], preview: "birthday-gymgirl-preview.png", full: "birthday-gymgirl.png" },
  "birthday-gymboy": { title: "Gym Bro Birthday", description: "A colourful birthday card.", categories: ["all", "for-him", "birthdays"], preview: "birthday-gymboy-preview.png", full: "birthday-gymboy.png" },
  "birthday-f1-racer": { title: "F1 Racer", description: "A colourful birthday card.", categories: ["all", "for-him", "birthdays", "children"], preview: "birthday-f1-racer-preview.png", full: "birthday-f1-racer.png" },
  "birthday-cake1": { title: "Birthday Cake", description: "A colourful birthday card.", categories: ["all", "for-her", "birthdays"], preview: "birthday-cake1-preview.png", full: "birthday-cake1.png" },
  "birthday-baking-girl": { title: "Baking Girls Birthday", description: "A colourful birthday card.", categories: ["all", "for-her", "birthdays"], preview: "birthday-baking-girl-preview.png", full: "birthday-baking.png" },
  "birthday-beachhut": { title: "Beach Hut Birthday", description: "A colourful birthday card.", categories: ["all", "for-him", "for-her", "birthdays"], preview: "birthday-beachhut-preview.png", full: "birthday-beachhut.png" },
  "birthday-coffee-cake": { title: "Coffee & Cake", description: "A colourful birthday card.", categories: ["all", "for-her", "birthdays"], preview: "birthday-coffee-cake-preview.png", full: "birthday-coffee-cake.png" },
  "birthday-flowers": { title: "Birthday Flowers", description: "A colourful birthday card.", categories: ["all", "for-her", "birthdays"], preview: "birthday-flowers-preview.png", full: "birthday-flowers.png" },
  "birthday-vintagegolf": { title: "Vintage Golfer", description: "A colourful birthday card.", categories: ["all", "for-him", "birthdays", "golf", "sports"], preview: "birthday-vintagegolf-preview.png", full: "birthday-vintagegolf.png" },
  "birthday-vintagefootball": { title: "Vintage Footballer", description: "A colourful birthday card.", categories: ["all", "for-him", "birthdays", "football", "sports"], preview: "birthday-vintagefootball-preview.png", full: "birthday-vintagefootball.png" },
  "birthday-vintagefishing": { title: "Vintage Fishing", description: "A colourful birthday card.", categories: ["all", "for-him", "birthdays", "sports"], preview: "birthday-vintagefishing-preview.png", full: "birthday-vintagefishing.png" },
  "birthday-lavenderfield": { title: "Lavender Field", description: "A colourful birthday card.", categories: ["all", "for-her", "birthdays"], preview: "birthday-lavenderfield-preview.png", full: "birthday-lavenderfield.png" },
  "birthday-bikers": { title: "Biker Boy", description: "A colourful birthday card.", categories: ["all", "for-him", "birthdays"], preview: "birthday-bikers-preview.png", full: "birthday-bikers.png" },
  "birthday-cupcakes": { title: "Birthday Cupcakes", description: "A colourful birthday card.", categories: ["all", "for-her", "birthdays"], preview: "birthdaycupcakes-preview.png", full: "birthdaycupcakes.png" },
  
  "birthday-grandad-horseracingtv": { title: "Grandad's Horse Racing", description: "A horse racing themed birthday card - perfect for the racing fan in your life.", categories: ["grandad","birthdays", "horseracing"], preview: "birthday-grandad-horseracingtv-preview.png", full: "birthday-grandad-horseracingtv.png" },
  "birthday-grandad-football-girl": { title: "Grandad & Granddaughter Football", description: "A warm birthday card celebrating time spent with the family.", categories: ["birthdays", "grandad"], preview: "birthday-grandad-football-girl-preview.png", full: "birthday-grandad-football-girl.png" },
  "birthday-grandad-football-garden": { title: "Grandad's Garden Football", description: "A warm birthday card celebrating time spent with the family.", categories: ["birthdays", "grandad"], preview: "birthday-grandad-football-garden-preview.png", full: "birthday-grandad-football-garden.png" },
  "birthday-grandad-catch-girl": { title: "Grandad & Granddaughter Playing Catch", description: "A warm birthday card celebrating time spent with the family.", categories: ["grandad", "birthdays"], preview: "birthday-grandad-catch-girl-preview.png", full: "birthday-grandad-catch-girl.png" },
  "birthday-grandad-fishing-boy": { title: "Grandad & Grandson Fishing", description: "A warm birthday card celebrating time spent with the family.", categories: ["birthdays", "grandad"], preview: "birthday-grandad-fishing-preview.png", full: "birthday-grandad-fishing.png" },
  "birthday-grandads-caravan": { title: "Grandads Caravan", description: "A warm birthday card celebrating time spent with the family.", categories: ["all", "birthdays", "grandad"], preview: "grandads-caravan-preview.png", full: "grandads-caravan.png" },
  
  "birthday-greatestmum": { title: "Greatest Mum Birthday", description: "A colourful birthday card.", categories: ["all", "for-her", "mum", "birthdays"], preview: "greatestmum-preview.png", full: "greatestmum.png" },
  "birthday-super-mum": { title: "Super Mum", description: "A colourful birthday card.", categories: ["all", "for-her", "mum", "birthdays"], preview: "super-mum-preview.png", full: "my-super-mum.png" },
  "birthday-best-mum-ever": { title: "Best Mum Ever", description: "A colourful birthday card.", categories: ["all", "for-her", "mum", "birthdays"], preview: "best-mum-ever-preview.png", full: "best-mum-ever.png" },
  "birthday-superbusy-mum": { title: " Super Busy Mum", description: "A colourful birthday card.", categories: ["all", "for-her", "mum", "birthdays"], preview: "superbusy-mum-preview.png", full: "superbusy-mum.png" },
  "birthday-mum-photo1": { title: "Happy Birthday Mum", price: "£3.49", description: "A personalised birthday card - add a favourite photo.", categories: ["mum", "birthdays", "photo-upload"], preview: "mum-photo1-preview.png", full: "mum-photo1.png",
    photo: { left: 890, top: 500, width: 408.1, height: 340 } },

  "birthday-dad-photo1": { title: "Happy Birthday Dad", price: "£3.49", description: "A personalised birthday card - add a favourite photo.", categories: ["dad", "birthdays", "photo-upload"], preview: "dad-photo1-preview.png", full: "dad-photo1.png",
    photo: { left: 896, top: 470, width: 440, height: 350 } },
  
  "birthday-handsomehubby": { title: "Handsome Hubby Birthday", price: "£3.49", description: "A personalised birthday card - add a favourite photo.", categories: ["all", "for-him", "birthdays", "photo-upload"], preview: "handsomehubby-preview.png", full: "handsomehubby.png",
    photo: { left: 870, top: 300, width: 400, height: 380 } },
  
  "birthday-nan-puddles": { title: "Puddles with Nan", description: "A birthday card for anyone who loves their yoga or pilates class.", categories: ["all", "for-her", "nan", "birthdays"], preview: "nan-puddles-preview.png", full: "nan-puddles.png" },
  "birthday-baking-nan": { title: "Nans Bakery", description: "A birthday card for anyone who loves their yoga or pilates class.", categories: ["all", "for-her", "nan", "birthdays"], preview: "baking-nan-preview.png", full: "baking-nan.png" },
  "birthday-nans-garden": { title: "Nans Garden", description: "A birthday card for anyone who loves their yoga or pilates class.", categories: ["all", "for-her", "nan", "birthdays"], preview: "nansgarden-preview.png", full: "nansgarden.png" },
  "birthday-nan1": { title: "Nans Country Garden", description: "A warm birthday card celebrating time spent with the family.", categories: ["nan", "birthdays"], preview: "birthday-nan1-preview.png", full: "birthday-nan1.png" },
  
  "birthday-butterflies": { title: "Birthday Butterflies", description: "A colourful birthday card.", categories: ["all", "for-her", "birthdays"], preview: "birthdaybutterflies-preview.png", full: "birthdaybutterflies.png" },
  "birthday-bbqboss": { title: "BBQ Boss Birthday", description: "A fun birthday card for someone who loves a cold drink or a good BBQ.", categories: ["all", "for-him", "birthdays"], preview: "bbqboss-preview.png", full: "bbqboss.png", name: { left: 894, top: 287, startSize: 68, minSize: 68, maxSize: 70, fontFamily: "Anton", fontWeight: "normal", color: "#feeec6", canChangeSize: false, canChangeColor: false, canMove: false, canRotate: false, isCurved: false, curveRadius: 700, tiltAngle: 0, label: "Name", maxChars: 9 } },
  "birthday-djboy": { title: "DJ Boy Card", description: "A birthday card for the party-starter in your life.", categories: ["all", "for-him", "birthdays"], preview: "dj-boy-preview.png", full: "dj-boy.png" },
  "birthday-gamer-boy": { title: "Game Boy", description: "A birthday card for the gamer in your life.", categories: ["all", "for-him", "birthdays", "children"], preview: "gaming-boy-preview.png", full: "gaming-boy.png" },
  "birthday-gamer-girl": { title: "Game Girl", description: "A birthday card for the gamer in your life.", categories: ["all", "for-her", "birthdays", "children"], preview: "gaming-girl-preview.png", full: "gaming-girl.png" },
  "birthday-gamer-fortnite-boy": { title: "Fortnite Boy", description: "A birthday card for the gamer in your life.", categories: ["all", "for-him", "birthdays", "children"], preview: "gaming-fortnite-boy-preview.png", full: "gaming-fortnite-boy.png", name: { left: 890, top: 331, startSize: 88, minSize: 80, maxSize: 95, fontFamily: "Anton", fontWeight: "normal", color: "#ffc700", canChangeSize: false, canChangeColor: false, canMove: false, canRotate: false, isCurved: false, curveRadius: 500, tiltAngle: 0, label: "Name", maxChars: 9 } },
  "birthday-gamer-fortnite-girl": { title: "Fortnite Girl", description: "A birthday card for the gamer in your life.", categories: ["all", "for-her", "birthdays", "children"], preview: "gaming-fortnite-girl-preview.png", full: "gaming-fortnite-girl_.png", name: { left: 885, top: 270, startSize: 88, minSize: 75, maxSize: 90, fontFamily: "Anton", fontWeight: "normal", color: "#ffffff", canChangeSize: false, canChangeColor: false, canMove: false, canRotate: false, isCurved: false, curveRadius: 500, tiltAngle: 0, label: "Name", maxChars: 7 } },
  "birthday-ladies-lunch": { title: "Ladies Lunch Card", description: "A fun birthday card for a girls' day out.", categories: ["all", "for-her", "birthdays"], preview: "ladies-lunch-preview.png", full: "ladies-lunch.png" },
  "birthday-ladies-shopping": { title: "Ladies Shopping Card", description: "A fun birthday card for a girls' day out.", categories: ["all", "for-her", "birthdays"], preview: "ladies-shopping-preview.png", full: "ladies-shopping.png" },
  "birthday-bttf": { title: "Back to the Future TV Card", description: "A birthday card for fans of classic film and TV nostalgia.", categories: ["all", "birthdays", "tv-movies"], preview: "birthday-bttf_preview.png", full: "birthday-bttf.png" },
  "birthday-inbetweeners": { title: "The Inbetweeners TV Card", description: "A birthday card for fans of classic film and TV nostalgia.", categories: ["all", "birthdays", "tv-movies"], preview: "birthday-inbetweeners-preview.png", full: "birthday-inbetweeners.png" },
  "jaws-smile": { title: "JAWS Smile You Son of..", description: "A birthday card for fans of classic film and TV nostalgia.", categories: ["all", "for-him", "tv-movies", "birthdays"], preview: "jaws-smile-preview.png", full: "jaws-smile.png" },
  "jaws-cake": { title: "JAWS Your Gonna Need a Bigger...", description: "A birthday card for fans of classic film and TV nostalgia.", categories: ["all", "for-him", "tv-movies", "birthdays"], preview: "jaws-biggercake-preview.png", full: "jaws-biggercake.png" },
  "birthday-ofah": { title: "OFAH, You Plonker!!", description: "A birthday card for fans of classic film and TV nostalgia.", categories: ["all", "birthdays", "tv-movies"], preview: "birthday-ofah_preview.png", full: "birthday-ofah.png" },
  "birthday-mod": { title: "Mod Birthday", description: "A birthday card for fans of classic film nostalgia.", categories: ["all", "birthdays", "tv-movies"], preview: "mod-birthday-preview.png", full: "mod-birthday.png" },
  "birthday-youngones": { title: "The Young Ones", description: "A birthday card for fans of classic film and TV nostalgia.", categories: ["all", "birthdays", "tv-movies"], preview: "birthday-youngones-preview.png", full: "birthday-youngones.png" },
  "birthday-charlie-says": { title: "Charlie Says..", description: "A birthday card for fans of classic film and TV nostalgia.", categories: ["all", "for-him", "birthdays"], preview: "charlie-says-preview.png", full: "charlie-says.png" },
  "birthday-wine-girls": { title: "Wine Girls Card", description: "A fun birthday card for someone who loves a glass of wine with friends.", categories: ["all", "for-her", "birthdays"], preview: "wine-girls-preview.png", full: "wine-girls.png" },
  "birthday-dad-learntoride": { title: "Learning to Ride a Bike", description: "A birthday card for anyone who loves their yoga or pilates class.", categories: ["all", "for-him", "dad", "birthdays"], preview: "dad-learntoride-preview.png", full: "dad-learntoride.png" },
  "birthday-dad-diydad": { title: "DIY Dad", description: "A birthday card for anyone who loves their yoga or pilates class.", categories: ["all", "for-him", "dad", "birthdays"], preview: "dad-diydad-preview.png", full: "dad-diydad.png" },
  "birthday-fabbirthday": { title: "Fab Birthday", description: "A birthday card for anyone who loves their yoga or pilates class.", categories: ["all", "birthdays"], preview: "fabbirthday-preview.png", full: "fabbirthday.png" },
  "birthday-boys-party": { title: "Boys Birthday Party", description: "A birthday card for anyone who loves their yoga or pilates class.", categories: ["children", "birthdays"], preview: "boys-party-preview.png", full: "boys-party.png" },
  "birthday-dinos-birthday": { title: "Dinos Birthday", description: "A birthday card for anyone who loves their yoga or pilates class.", categories: ["children", "birthdays"], preview: "dinos-birthday-preview.png", full: "dinos-birthday.png" },
  "birthday-girls-party": { title: "Girls Birthday Party", description: "A birthday card for anyone who loves their yoga or pilates class.", categories: ["children", "birthdays"], preview: "girls-party-preview.png", full: "girls-party.png" },
  "birthday-boys-toys": { title: "Boys Toys", description: "A birthday card for anyone who loves their yoga or pilates class.", categories: ["children", "birthdays"], preview: "boys-toys-preview.png", full: "boys-toys.png" },
  "birthday-girls-toys": { title: "Girls Toys", description: "A birthday card for anyone who loves their yoga or pilates class.", categories: ["children", "birthdays"], preview: "girls-toys-preview.png", full: "girls-toys.png" },
  "birthday-girls-toys": { title: "Girls Toys", description: "A birthday card for anyone who loves their yoga or pilates class.", categories: ["children", "birthdays"], preview: "girls-toys-preview.png", full: "girls-toys.png" },
  "birthday-minecraft-girly": { title: "Minecraft Girl", description: "A birthday card for anyone who loves their yoga or pilates class.", categories: ["children", "birthdays"], preview: "minecraft-girly-preview.png", full: "minecraft-girly.png" },
  "birthday-minecraft-boy": { title: "Minecraft Birthday Boy", description: "S.", categories: ["children", "birthdays"], price: "£3.49", preview: "minecraft-boy1-preview.png", full: "minecraft-boy.png", name: { left: 895, top: 290, startSize: 80, minSize: 35, maxSize: 60, fontFamily: "CaacupeOne-Regular", fontWeight: "bold", color: "#004aad", canChangeSize: false, canChangeColor: false, canMove: true, canRotate: false, isCurved: false, curveRadius: 0, tiltAngle: 0, label: "Name", maxChars: 9 } },
  "birthday-minecraft-girl": { title: "Minecraft Birthday Girl", description: "S.", categories: ["children", "birthdays"], price: "£3.49", preview: "minecraft-girl1-preview.png", full: "minecraft-girl1.png", name: { left: 894, top: 744, startSize: 110, minSize: 35, maxSize: 60, fontFamily: "CaacupeOne-Regular", fontWeight: "bold", color: "#5e17eb", canChangeSize: false, canChangeColor: false, canMove: true, canRotate: false, isCurved: false, curveRadius: 0, tiltAngle: 0, label: "Name", maxChars: 9 } },
  

  "birthday-taxi": { title: "Birthday Taxi", price: "£3.49", description: "A fun birthday card - add a photo and their name for a personal touch.", categories: ["all", "for-him", "birthdays", "photo-upload"], preview: "birthday-taxi-preview.png", full: "birthday-taxi.png", name: { left: 895, top: 668, startSize: 27, minSize: 28, maxSize: 28, maxSize: 86, fontFamily: "Anton", fontWeight: "normal", color: "#000000", canChangeSize: false, canChangeColor: false, canMove: false, canRotate: false, isCurved: false, curveRadius: 480, tiltAngle: 0, label: "Name", maxChars: 10 },
    // Round gold-ringed photo window near the top of the card — measured
    // from the artwork itself, NOT the generic default box. left/top is
    // the center of the circle; width/height is a square slightly larger
    // than the circle's diameter (the artwork's own round cutout does the
    // actual round clipping, so the square only needs to fully cover it).
    photo: { left: 733, top: 178, width: 240, height: 230 } },
  
  
  "drivingtest-boy1": { title: "Driving Test Pass Boy", description: "Celebrate passing their driving test with this fun congratulations card.", categories: ["all", "for-him", "achievements"], preview: "drivingtest-boy1-preview.png", full: "drivingtest-boy1.png",
    variants: [
      { id: "drivingtest-boy1-brown", full: "drivingtest-boy3.png" },
      { id: "drivingtest-boy1-blonde", full: "drivingtest-boy2.png" },
    ] },                   
  
  "drivingtest-girl1": { title: "Driving Test Pass Girl", description: "Celebrate passing their driving test with this fun congratulations card.", categories: ["all", "for-her", "achievements"], preview: "drivingtest-girl1-preview.png", full: "drivingtest-girl1.png",
    variants: [
      { id: "drivingtest-girl1-brown", full: "drivingtest-girl3.png" },
      { id: "drivingtest-girl1-blonde", full: "drivingtest-girl2.png" },
    ] },
  "drivingtestboy": { title: "Driving Pass Congratulations Boy", description: "Celebrate passing their driving test with this fun congratulations card.", categories: ["all", "for-him", "achievements"], preview: "drivingtestboy-preview.png", full: "drivingtestboy.png" },
  "drivingtest-girl4": { title: "Driving Pass Congratulations Girl", description: "Celebrate passing their driving test with this fun congratulations card.", categories: ["all", "for-her", "achievements"], preview: "drivingtest-girl4-preview.png", full: "drivingtest-girl4.png" },
  "learner1": { title: "Driving Test Pass Card", description: "Celebrate passing their driving test with this fun congratulations card.", categories: ["all", "for-him", "achievements"], preview: "learner1-preview.png", full: "learner1.png" },
  "learner2": { title: "Driving Test Pass Card Girl", description: "Celebrate passing their driving test with this fun congratulations card.", categories: ["all", "for-her", "achievements"], preview: "learner2-preview.png", full: "learner2.png" },
  
  "exams-boy": { title: "Exams Congratulations Card", description: "Congratulate them on their exam results with this celebration card.", categories: ["all", "for-him", "achievements"], preview: "exams-boy-preview.png", full: "exams-boy.png" },
  "exams-girl": { title: "Exams Congratulations Girl", description: "Congratulate them on their exam results with this celebration card.", categories: ["all", "for-her", "achievements"], preview: "exams-girl-preview.png", full: "exams-girl.png" },
  
  "leaving-boy": { title: "Sorry You're Leaving Boy", description: "Wish them well with this leaving card - perfect for a colleague moving on to new things.", categories: ["all", "for-him", "work-related"], preview: "leaving-boy-preview.png", full: "leaving-boy.png" },
  "leaving-girl": { title: "Sorry You're Leaving Girl", description: "Wish them well with this leaving card - perfect for a colleague moving on to new things.", categories: ["all", "for-her", "work-related"], preview: "leaving-girl-preview.png", full: "leaving-girl.png" },
  
  "new-home": { title: "Home Sweet Home", description: "Congratulate them on their new home with this card.", categories: ["all", "home"], preview: "newhome-preview.png", full: "newhome.png" },
  "new-home": { title: "Home Sweet Home", description: "Congratulate them on their new home with this card.", categories: ["all", "home"], preview: "newhome-happyhome-preview.png", full: "newhome-happyhome.png" },
  "newhome1": { title: "New Home, New Beginnings", description: "Congratulate them on their new home with this card.", categories: ["all", "home"], preview: "newhome1-preview.png", full: "newhome1.png" },
  "newhome2": { title: "New Home Unboxed", description: "Congratulate them on their new home with this card.", categories: ["all", "home"], preview: "newhome2-preview.png", full: "newhome2.png" },
  "newhome3": { title: "New Home, New Adventures", description: "Congratulate them on their new home with this card.", categories: ["all", "home"], preview: "newhome3-preview.png", full: "newhome3.png" },
  "newhome4": { title: "New Home Wishes", description: "Congratulate them on their new home with this card.", categories: ["all", "home"], preview: "newhome4-preview.png", full: "newhome4.png" },
  "newhome5": { title: "New Home Together", description: "Congratulate them on their new home with this card.", categories: ["all", "home"], preview: "newhome5-preview.png", full: "newhome5.jpg" },
  "newhome6": { title: "New Home, New Memories", description: "Congratulate them on their new home with this card.", categories: ["all", "home"], preview: "newhome6-preview.png", full: "newhome6.jpg" },
  "newhome7": { title: "New University Home", description: "Congratulate them on their new home with this card.", categories: ["all", "school-cards", "home"], preview: "newhome7-preview.png", full: "newhome7.jpg" },
  "newhome8": { title: "New Home, New Dreams", description: "Congratulate them on their new home with this card.", categories: ["all", "home"], preview: "newhome8-preview.png", full: "newhome8.png" },
  "newhome9": { title: "New Home Love", description: "Congratulate them on their new home with this card.", categories: ["all", "home"], preview: "newhome9-preview.png", full: "newhome9.png" },
  "newhome10": { title: "New Home, New Pad", description: "Congratulate them on their new home with this card.", categories: ["all", "home"], preview: "newhome10-preview.png", full: "newhome10.png" },

  "newbaby-beautifulbabygirl": { title: "Beautiful Baby Girl", description: "Welcome the new arrival with this new baby card.", categories: ["all", "newbaby"], preview: "newbaby-beautifulbabygirl-preview.png", full: "newbaby-beautifulbabygirl.png" },
  "newbaby-beautifulbabyboy": { title: "Beautiful Baby Boy", description: "Welcome the new arrival with this new baby card.", categories: ["all", "newbaby"], preview: "newbaby-beautifulbabyboy-preview.png", full: "newbaby-beautifulbabyboy.png" },
  "newbaby-hellolittleone": { title: "Hello Little One", description: "Welcome the new arrival with this new baby card.", categories: ["all", "newbaby"], preview: "newbaby-hellolittleone-preview.png", full: "newbaby-hellolittleone.png" },
  
  "newbaby-butterflies": { title: "Baby Butterflies", price: "£3.49", description: "Welcome the new arrival with this new baby card. Add a photo and their name.", categories: ["all", "newbaby", "photo-upload"], preview: "newbaby-butterflies-preview.png", full: "newbaby-butterflies.png", name: { left: 894, top: 620, startSize: 38, minSize: 34, maxSize: 34, maxSize: 34, fontFamily: "Anton", fontWeight: "normal", color: "#ffffff", canChangeSize: false, canChangeColor: false, canMove: false, canRotate: false, isCurved: false, curveRadius: 480, tiltAngle: 0, label: "Name", maxChars: 13 },
    photo: { left: 897, top: 405, width: 450, height: 350 } },
  
  "newbaby-itsagirl": { title: "It's a Girl", price: "£3.49", description: "Welcome the new arrival with this new baby card. Add a photo and their name.", categories: ["all", "newbaby", "photo-upload"], preview: "newbaby-itsagirl-preview.png", full: "newbaby-itsagirl.png", name: { left: 893, top: 635, startSize: 43, minSize: 28, maxSize: 28, maxSize: 86, fontFamily: "Anton", fontWeight: "normal", color: "#ffffff", canChangeSize: false, canChangeColor: false, canMove: false, canRotate: false, isCurved: false, curveRadius: 480, tiltAngle: 0, label: "Name", maxChars: 15 },
    photo: { left: 897, top: 465, width: 450, height: 250 } },
  
  "newbaby-underthesea": { title: "Under the Sea", price: "£3.49", description: "Welcome the new arrival with this new baby card. Add a photo and their name.", categories: ["all", "newbaby", "photo-upload"], preview: "newbaby-underthesea-preview.png", full: "newbaby-underthesea.png", name: { left: 889, top: 589, startSize: 37, minSize: 28, maxSize: 28, maxSize: 86, fontFamily: "Anton", fontWeight: "normal", color: "#ffffff", canChangeSize: false, canChangeColor: false, canMove: false, canRotate: false, isCurved: false, curveRadius: 480, tiltAngle: 0, label: "Name", maxChars: 12 },
    photo: { left: 895, top: 370, width: 470, height: 340 } },
  
  "newbaby-rainbows": { title: "Baby Rainbows", price: "£3.49", description: "Welcome the new arrival with this new baby card. Add a photo and their name.", categories: ["all", "newbaby", "photo-upload"], preview: "newbaby-rainbows-preview.png", full: "newbaby-rainbows.png", name: { left: 895, top: 623, startSize: 38, minSize: 28, maxSize: 28, maxSize: 86, fontFamily: "Anton", fontWeight: "normal", color: "#ffffff", canChangeSize: false, canChangeColor: false, canMove: false, canRotate: false, isCurved: false, curveRadius: 480, tiltAngle: 0, label: "Name", maxChars: 13 },
    photo: { left: 894, top: 415, width: 465, height: 325 } },
  
  "newbaby-spacebaby": { title: "Space Teddy", price: "£3.49", description: "Welcome the new arrival with this new baby card. Add a photo and their name.", categories: ["all", "newbaby", "photo-upload"], preview: "newbaby-spacebaby-preview.png", full: "newbaby-spacebaby.png", name: { left: 893, top: 623, startSize: 42, minSize: 28, maxSize: 28, maxSize: 86, fontFamily: "Anton", fontWeight: "normal", color: "#2d659a", canChangeSize: false, canChangeColor: false, canMove: false, canRotate: false, isCurved: false, curveRadius: 480, tiltAngle: 0, label: "Name", maxChars: 13 },
    photo: { left: 894, top: 413, width: 350, height: 330 } },
  
  "fathers-day-peaky": { title: "Fathers Day Peaky Dad", description: "A lovely card to celebrate Father's Day.", categories: ["mothersday-fathersday"], preview: "fathers-day-peaky-preview.png", full: "fathers-day-peaky.png" },
  "fathers-day-pub": { title: "Fathers Day Pub", description: "A lovely card to celebrate Father's Day.", categories: ["mothersday-fathersday"], preview: "fathers-day-pub-preview.png", full: "fathers-day-pub.png" },
  "fathers-day-sopranos": { title: "Fathers Day Sopranos Dad", description: "A lovely card to celebrate Father's Day.", categories: ["mothersday-fathersday"], preview: "fathers-day-sopranos-preview.png", full: "fathers-day-sopranos.png" },
  "fathers-day-godfather": { title: "Fathers Day Godfather Dad", description: "A lovely card to celebrate Father's Day.", categories: ["mothersday-fathersday"], preview: "fathers-day-godfather-preview.png", full: "fathers-day-godfather.png" },
  
  "teaching-assistant1": { title: "Best Teaching Assistant", description: "Say a well-deserved thank you to a brilliant teacher or teaching assistant.", categories: ["all", "for-her", "school-cards", "thank-you"], preview: "teaching-assistant1-preview.png", full: "teaching-assistant1.png" },
  "teaching-assistant2": { title: "Teaching Assistant, Thank you", description: "Say a well-deserved thank you to a brilliant teacher or teaching assistant.", categories: ["all", "for-her", "school-cards", "thank-you"], preview: "teaching-assistant2-preview.png", full: "teaching-assistant2.png" },
  "thankyou-teacher1": { title: "Teacher, Thank You!", description: "Say a well-deserved thank you to a brilliant teacher or teaching assistant.", categories: ["all", "for-her", "school-cards", "thank-you"], preview: "thankyou-teacher1-preview.png", full: "thankyou-teacher.png" },
  "superteacher-boy": { title: "Greatest Teacher", description: "Say a well-deserved thank you to a brilliant teacher or teaching assistant.", categories: ["all", "for-him", "school-cards", "thank-you"], preview: "superteacher-boy-preview.png", full: "superteacher-boy.png" },
  "superteacher-girl": { title: "Super Teacher", description: "Say a well-deserved thank you to a brilliant teacher or teaching assistant.", categories: ["all", "for-her", "school-cards", "thank-you"], preview: "superteacher-girl-preview.png", full: "superteacher-girl.png" },
  "thankyou-teacher": { title: "Thank You, Teacher Card", description: "Say a well-deserved thank you to a brilliant teacher or teaching assistant.", categories: ["all", "school-cards", "thank-you"], price: "£3.49", preview: "thankyou-teacher-preview.png", full: "thankyou-teacher.png", name: { left: 897, top: 728, startSize: 52, minSize: 35, maxSize: 60, fontFamily: "BubblegumSans", fontWeight: "bold", color: "#FD7D96", canChangeSize: true, canChangeColor: true, canMove: false, canRotate: false, isCurved: false, curveRadius: 0, tiltAngle: 0, label: "Name", maxChars: 14 } },
  
  "mothers-day1": { title: "Mothers Day", description: "A lovely card to celebrate Mother's Day.", categories: ["mothersday-fathersday"], preview: "mothers-day1-preview.png", full: "mothers-day1.png" },
  "mothers-day2": { title: "Mothers Day", description: "A lovely card to celebrate Mother's Day.", categories: ["mothersday-fathersday"], preview: "mothers-day2-preview.png", full: "mothers-day2.png" },
  "mothers-day3": { title: "Mothers Day", description: "A lovely card to celebrate Mother's Day.", categories: ["mothersday-fathersday"], preview: "mothers-day3-preview.png", full: "mothers-day3.png" },

  "engagement1": { title: "Engagement Hearts", description: "Celebrate their engagement with this card.", categories: ["all", "for-her", "weddings-engagements"], preview: "engagement1-preview.png", full: "engagement1.png" },
  "engagement2": { title: "Engagement Bubbles", description: "Celebrate their engagement with this card.", categories: ["all", "for-her", "weddings-engagements"], preview: "engagement2-preview.png", full: "engagement2.png" },
  "engagement3": { title: "She Said Yes!", description: "Celebrate their engagement with this card.", categories: ["all", "for-her", "weddings-engagements"], preview: "engagement3-preview.png", full: "engagement3.png" },
  "engagement4": { title: "Engagement Ring Card", description: "Celebrate their engagement with this card.", categories: ["all", "for-her", "weddings-engagements"], preview: "engagement4-preview.png", full: "engagement4.png" },
  "engagement5": { title: "The Propsal", description: "Celebrate their engagement with this card.", categories: ["all", "for-her", "weddings-engagements"], preview: "engagement5-preview.png", full: "engagement5.png" },

  "wedding1": { title: "Over the Threshold", description: "Celebrate their wedding day with this card.", categories: ["all", "for-her", "weddings-engagements"], preview: "wedding-overthethreshold-preview.png", full: "wedding-overthethreshold.png" },
  "wedding2": { title: "Wedding Bubbles", description: "Celebrate their wedding day with this card.", categories: ["all", "for-her", "weddings-engagements"], preview: "wedding-bubbles-preview.png", full: "wedding-bubbles.png" },
  "wedding3": { title: "Just Married", description: "Celebrate their wedding day with this card.", categories: ["all", "for-her", "weddings-engagements"], preview: "wedding-car-justmarried-preview.png", full: "wedding-car-justmarried.png" },

  "happy-hen-party1": { title: "Hen Party Girls", description: "A fun card to celebrate the bride-to-be's hen party.", categories: ["all", "for-her", "weddings-engagements"], preview: "happy-hen-party1-preview.png", full: "happy-hen-party1.png" },
  "happy-hen-party2": { title: "Hen Party Sleep Over", description: "A fun card to celebrate the bride-to-be's hen party.", categories: ["all", "for-her", "weddings-engagements"], preview: "happy-hen-party2-preview.png", full: "happy-hen-party2.png" },

  "christmas-santas-christmas": { title: "Santa's Christmas", description: "A festive Christmas card for the whole family.", categories: ["christmas"], preview: "christmas-santa-preview.png", full: "christmas-santa.png" },
  "christmas-nicest-children": { title: "Santa's Nicest Children", price: "£3.49", description: "A festive Christmas card for the whole family. Add a family photo to make it extra special.", categories: ["christmas"], preview: "nicest-children-preview.png", full: "nicest-children.png",
    photo: { left: 909.6, top: 331.3, width: 408.1, height: 385.4 } },
 "christmas-naughtyornice": { title: "Santa's Naughty or Nice? (Video Card)", price: "£3.49", description: "A festive Christmas card with a video message from Santa they can scan to watch.", categories: ["christmas"], preview: "santa-video-preview.png", full: "santa-video.png",
    qr: { left: 915, top: 686, width: 130, height: 130, url: "https://images.cockneycards.com/santas-message-qr.png" } },

//SPORTS

  "afc-ladies-celebrating": { title: "Arsenal Ladies Celebrating Card", description: "A celebration card for Arsenal fans.", categories: ["sports", "football", "wsl", "arsenal"], preview: "afc-ladies-celebrating-preview.png", full: "afc-ladies-celebrating.png" },
  
  "afc-ladies-shirt1": { title: "Arsenal Ladies Shirt Card", description: "A personalised Arsenal shirt card - add their name and squad number to the back of the shirt.", categories: ["sports", "football", "wsl", "arsenal"], price: "£3.49", preview: "afc-ladies-shirt1-preview.png", full: "afc-ladies-shirt1.png", name: { left: 882, top: 519, startSize: 28, minSize: 20, maxSize: 30, fontFamily: "Anton", fontWeight: "normal", color: "#FFFFFF", canChangeSize: false, canChangeColor: false, canMove: false, canRotate: false, isCurved: true, curveRadius: 150, tiltAngle: 0, label: "Name", maxChars: 7 }, age: { left: 882, top: 577, startSize: 60, minSize: 20, maxSize: 120, fontFamily: "Anton", fontWeight: "normal", color: "#FFFFFF", canChangeSize: true, canChangeColor: true, label: "Shirt", maxChars: 2, numericOnly: true, lettersOnly: false, forceUppercase: false, defaultText: "10" } },
  "afc-ladies-shirt2": { title: "Arsenal Ladies Shirt Card", description: "A personalised Arsenal shirt card - add their name and squad number to the back of the shirt.", categories: ["sports", "football", "wsl", "arsenal"], price: "£3.49", preview: "afc-ladies-shirt2-preview.png", full: "afc-ladies-shirt2.png", name: { left: 882, top: 519, startSize: 28, minSize: 20, maxSize: 30, fontFamily: "Anton", fontWeight: "normal", color: "#FFFFFF", canChangeSize: false, canChangeColor: false, canMove: false, canRotate: false, isCurved: true, curveRadius: 150, tiltAngle: 0, label: "Name", maxChars: 7 }, age: { left: 882, top: 577, startSize: 60, minSize: 20, maxSize: 120, fontFamily: "Anton", fontWeight: "normal", color: "#FFFFFF", canChangeSize: true, canChangeColor: true, label: "Shirt", maxChars: 2, numericOnly: true, lettersOnly: false, forceUppercase: false, defaultText: "10" } },
  
  "afc-men-shirt1": { title: "Arsenal Shirt Card", description: "A personalised Arsenal shirt card - add their name and squad number to the back of the shirt.", categories: ["sports", "football", "premiership", "arsenal"], price: "£3.49", preview: "afc-men-shirt1-preview.png", full: "afc-men-shirt1.png", name: { left: 880, top: 492, startSize: 30, minSize: 20, maxSize: 30, fontFamily: "Anton", fontWeight: "normal", color: "#FFFFFF", canChangeSize: false, canChangeColor: false, canMove: false, canRotate: false, isCurved: true, curveRadius: 150, tiltAngle: 0, label: "Name", maxChars: 7 }, age: { left: 880, top: 555, startSize: 70, minSize: 20, maxSize: 120, fontFamily: "Anton", fontWeight: "normal", color: "#FFFFFF", canChangeSize: true, canChangeColor: true, label: "Shirt", maxChars: 2, numericOnly: true, lettersOnly: false, forceUppercase: false, defaultText: "10" } },
  "afc-men-shirt2": { title: "Arsenal Shirt Card", description: "A personalised Arsenal shirt card - add their name and squad number to the back of the shirt.", categories: ["sports", "football", "premiership", "arsenal"], price: "£3.49", preview: "afc-men-shirt2-preview.png", full: "afc-men-shirt2.png", name: { left: 880, top: 493, startSize: 30, minSize: 20, maxSize: 30, fontFamily: "Anton", fontWeight: "normal", color: "#FFFFFF", canChangeSize: false, canChangeColor: false, canMove: false, canRotate: false, isCurved: true, curveRadius: 150, tiltAngle: 0, label: "Name", maxChars: 7 }, age: { left: 880, top: 555, startSize: 70, minSize: 20, maxSize: 120, fontFamily: "Anton", fontWeight: "normal", color: "#FFFFFF", canChangeSize: true, canChangeColor: true, label: "Shirt", maxChars: 2, numericOnly: true, lettersOnly: false, forceUppercase: false, defaultText: "10" } },
  

  "f1-ferrari": { title: "Ferrari F1 Driver", description: "A beautifully designed racing card ready to personalise.", categories: ["sports", "formula1"], price: "£3.49", preview: "f1-ferrari-preview.png", full: "f1-ferrari.png", name: { left: 892, top: 300, startSize: 90, minSize: 90, maxSize: 35, fontFamily: "Anton", fontWeight: "normal", color: "#ffffff", canChangeSize: false, canChangeColor: false, canMove: false, canRotate: false, isCurved: false, curveRadius: 0, tiltAngle: 0, label: "Name", maxChars: 10 }, age: { left: 888, top: 485, startSize: 66, minSize: 20, maxSize: 120, fontFamily: "Anton", fontWeight: "normal", color: "#ffffff", canChangeSize: false, canChangeColor: true, label: "Shirt", maxChars: 2, numericOnly: true, lettersOnly: false, forceUppercase: false, defaultText: "10" } },
  "f1-mclaren": { title: "McLaren F1 Driver", description: "A beautifully designed racing card ready to personalise.", categories: ["sports", "formula1"], price: "£3.49", preview: "f1-mclaren-preview.png", full: "f1-mclaren.png", name: { left: 891, top: 300, startSize: 90, minSize: 90, maxSize: 35, fontFamily: "Anton", fontWeight: "normal", color: "#ffffff", canChangeSize: false, canChangeColor: false, canMove: false, canRotate: false, isCurved: false, curveRadius: 0, tiltAngle: 0, label: "Name", maxChars: 10 }, age: { left: 889, top: 485, startSize: 66, minSize: 20, maxSize: 120, fontFamily: "Anton", fontWeight: "normal", color: "#ffffff", canChangeSize: false, canChangeColor: true, label: "Shirt", maxChars: 2, numericOnly: true, lettersOnly: false, forceUppercase: false, defaultText: "10" } },
  "f1-mercedes": { title: "Mercedes F1 Driver", description: "A beautifully designed racing card ready to personalise.", categories: ["sports", "formula1"], price: "£3.49", preview: "f1-mercedes-preview.png", full: "f1-mercedes.png", name: { left: 893, top: 300, startSize: 90, minSize: 30, maxSize: 35, fontFamily: "Anton", fontWeight: "normal", color: "#ffffff", canChangeSize: false, canChangeColor: false, canMove: false, canRotate: false, isCurved: false, curveRadius: 0, tiltAngle: 0, label: "Name", maxChars: 10 }, age: { left: 888, top: 485, startSize: 66, minSize: 20, maxSize: 120, fontFamily: "Anton", fontWeight: "normal", color: "#ffffff", canChangeSize: false, canChangeColor: true, label: "Shirt", maxChars: 2, numericOnly: true, lettersOnly: false, forceUppercase: false, defaultText: "10" } },
  "f1-redbull": { title: "Redbull F1 Driver", description: "A beautifully designed racing card ready to personalise.", categories: ["sports", "formula1"], price: "£3.49", preview: "f1-redbull-preview.png", full: "f1-redbull.png", name: { left: 893, top: 300, startSize: 90, minSize: 30, maxSize: 35, fontFamily: "Anton", fontWeight: "normal", color: "#ffffff", canChangeSize: false, canChangeColor: false, canMove: false, canRotate: false, isCurved: false, curveRadius: 0, tiltAngle: 0, label: "Name", maxChars: 10 }, age: { left: 888, top: 485, startSize: 66, minSize: 20, maxSize: 120, fontFamily: "Anton", fontWeight: "normal", color: "#ffffff", canChangeSize: false, canChangeColor: true, label: "Shirt", maxChars: 2, numericOnly: true, lettersOnly: false, forceUppercase: false, defaultText: "10" } },
  "f1-williams": { title: "Williams F1 Driver", description: "A beautifully designed racing card ready to personalise.", categories: ["sports", "formula1"], price: "£3.49", preview: "f1-williams-preview.png", full: "f1-williams.png", name: { left: 885, top: 300, startSize: 90, minSize: 30, maxSize: 35, fontFamily: "Anton", fontWeight: "normal", color: "#ffffff", canChangeSize: false, canChangeColor: false, canMove: false, canRotate: false, isCurved: false, curveRadius: 0, tiltAngle: 0, label: "Name", maxChars: 10 }, age: { left: 881, top: 485, startSize: 66, minSize: 20, maxSize: 120, fontFamily: "Anton", fontWeight: "normal", color: "#ffffff", canChangeSize: false, canChangeColor: true, label: "Shirt", maxChars: 2, numericOnly: true, lettersOnly: false, forceUppercase: false, defaultText: "10" } },
  "f1-alpine": { title: "Alpine F1 Driver", description: "A beautifully designed racing card ready to personalise.", categories: ["sports", "formula1"], price: "£3.49", preview: "f1-alpine-preview.png", full: "f1-alpine.png", name: { left: 891, top: 300, startSize: 90, minSize: 30, maxSize: 35, fontFamily: "Anton", fontWeight: "normal", color: "#ffffff", canChangeSize: false, canChangeColor: false, canMove: false, canRotate: false, isCurved: false, curveRadius: 0, tiltAngle: 0, label: "Name", maxChars: 10 }, age: { left: 884, top: 485, startSize: 66, minSize: 20, maxSize: 120, fontFamily: "Anton", fontWeight: "normal", color: "#ffffff", canChangeSize: false, canChangeColor: true, label: "Shirt", maxChars: 2, numericOnly: true, lettersOnly: false, forceUppercase: false, defaultText: "10" } },
  "f1-astonmartin": { title: "Aston Martin F1 Driver", description: "A beautifully designed racing card ready to personalise.", categories: ["sports", "formula1"], price: "£3.49", preview: "f1-aston-preview.png", full: "f1-aston.png", name: { left: 893, top: 300, startSize: 90, minSize: 30, maxSize: 35, fontFamily: "Anton", fontWeight: "normal", color: "#ffffff", canChangeSize: false, canChangeColor: false, canMove: false, canRotate: false, isCurved: false, curveRadius: 0, tiltAngle: 0, label: "Name", maxChars: 10 }, age: { left: 888, top: 485, startSize: 66, minSize: 20, maxSize: 120, fontFamily: "Anton", fontWeight: "normal", color: "#ffffff", canChangeSize: true, canChangeColor: true, label: "Shirt", maxChars: 2, numericOnly: true, lettersOnly: false, forceUppercase: false, defaultText: "10" } },
  "f1-audi": { title: "Audi F1 Driver", description: "A beautifully designed racing card ready to personalise.", categories: ["sports", "formula1"], price: "£3.49", preview: "f1-audi-preview.png", full: "f1-audi.png", name: { left: 893, top: 300, startSize: 90, minSize: 30, maxSize: 35, fontFamily: "Anton", fontWeight: "normal", color: "#ffffff", canChangeSize: false, canChangeColor: false, canMove: false, canRotate: false, isCurved: false, curveRadius: 0, tiltAngle: 0, label: "Name", maxChars: 10 }, age: { left: 888, top: 485, startSize: 66, minSize: 20, maxSize: 120, fontFamily: "Anton", fontWeight: "normal", color: "#ffffff", canChangeSize: false, canChangeColor: true, label: "Shirt", maxChars: 2, numericOnly: true, lettersOnly: false, forceUppercase: false, defaultText: "10" } },
  "f1-haas": { title: "Haas F1 Driver", description: "A beautifully designed racing card ready to personalise.", categories: ["sports", "formula1"], price: "£3.49", preview: "f1-haas-preview.png", full: "f1-haas.png", name: { left: 893, top: 300, startSize: 90, minSize: 30, maxSize: 35, fontFamily: "Anton", fontWeight: "normal", color: "#ffffff", canChangeSize: false, canChangeColor: false, canMove: false, canRotate: false, isCurved: false, curveRadius: 0, tiltAngle: 0, label: "Name", maxChars: 10 }, age: { left: 889, top: 485, startSize: 66, minSize: 20, maxSize: 120, fontFamily: "Anton", fontWeight: "normal", color: "#ffffff", canChangeSize: false, canChangeColor: true, label: "Shirt", maxChars: 2, numericOnly: true, lettersOnly: false, forceUppercase: false, defaultText: "10" } },
  
  "mcity-girl1": { title: "Man City Girl 1", description: "A beautifully designed \"Man City Girl 1\" card, ready to personalise.", categories: ["sports", "football", "wsl", "man-cityw"], price: "£3.49", preview: "mcity-girl1-preview.png", full: "mcity-girl1.png", name: { left: 891, top: 344, startSize: 28, minSize: 26, maxSize: 30, fontFamily: "Anton", fontWeight: "normal", color: "#001130", canChangeSize: true, canChangeColor: false, canMove: false, canRotate: false, isCurved: true, curveRadius: 150, tiltAngle: 0, label: "Name", maxChars: 12 }, age: { left: 891, top: 400, startSize: 68, minSize: 20, maxSize: 120, fontFamily: "Anton", fontWeight: "normal", color: "#001130", canChangeSize: true, canChangeColor: true, label: "Shirt", maxChars: 2, numericOnly: true, lettersOnly: false, forceUppercase: false, defaultText: "10" } },
  "mcity-girl2": { title: "Man City Girl 2", description: "A beautifully designed \"Man City Girl 2\" card, ready to personalise.", categories: ["sports", "football", "wsl", "man-cityw"], price: "£3.49", preview: "mcity-girl2-preview.png", full: "mcity-girl2.png", name: { left: 894, top: 348, startSize: 28, minSize: 26, maxSize: 30, fontFamily: "Anton", fontWeight: "normal", color: "#001130", canChangeSize: true, canChangeColor: false, canMove: false, canRotate: false, isCurved: true, curveRadius: 150, tiltAngle: 0, label: "Name", maxChars: 12 }, age: { left: 894, top: 410, startSize: 70, minSize: 20, maxSize: 120, fontFamily: "Anton", fontWeight: "normal", color: "#001130", canChangeSize: true, canChangeColor: true, label: "Shirt", maxChars: 2, numericOnly: true, lettersOnly: false, forceUppercase: false, defaultText: "10" } },
  "mcity-girl3": { title: "Man City Girl 3", description: "A beautifully designed \"Man City Girl 3\" card, ready to personalise.", categories: ["sports", "football", "wsl", "man-cityw"], price: "£3.49", preview: "mcity-girl3-preview.png", full: "mcity-girl3.png", name: { left: 888, top: 348, startSize: 28, minSize: 26, maxSize: 30, fontFamily: "Anton", fontWeight: "normal", color: "#001130", canChangeSize: true, canChangeColor: false, canMove: false, canRotate: false, isCurved: true, curveRadius: 150, tiltAngle: 0, label: "Name", maxChars: 12 }, age: { left: 888, top: 410, startSize: 70, minSize: 20, maxSize: 120, fontFamily: "Anton", fontWeight: "normal", color: "#001130", canChangeSize: true, canChangeColor: true, label: "Shirt", maxChars: 2, numericOnly: true, lettersOnly: false, forceUppercase: false, defaultText: "10" } },
  "mcity-girl4": { title: "Man City Girl 4", description: "A beautifully designed \"Man City Girl 4\" card, ready to personalise.", categories: ["sports", "football", "wsl", "man-cityw"], price: "£3.49", preview: "mcity-girl4-preview.png", full: "mcity-girl4.png", name: { left: 890, top: 349, startSize: 28, minSize: 26, maxSize: 30, fontFamily: "Anton", fontWeight: "normal", color: "#001130", canChangeSize: true, canChangeColor: false, canMove: false, canRotate: false, isCurved: true, curveRadius: 150, tiltAngle: 0, label: "Name", maxChars: 12 }, age: { left: 890, top: 410, startSize: 70, minSize: 20, maxSize: 120, fontFamily: "Anton", fontWeight: "normal", color: "#001130", canChangeSize: true, canChangeColor: true, label: "Shirt", maxChars: 2, numericOnly: true, lettersOnly: false, forceUppercase: false, defaultText: "10" } },

  "city-ladies-celebrating": { title: "City Ladies Celebrating Card", description: "A celebration card for football fans.", categories: ["sports", "football", "wsl", "man-cityw"], preview: "city-ladies-celebrating-preview.png", full: "city-ladies-celebrating.png" },
  
  "wham-girl1": { title: "West Ham Girl 1", description: "A beautifully designed \"West Ham Girl 1\" card, ready to personalise.", categories: ["sports", "football", "wsl", "westhamw"], price: "£3.49", preview: "wham-girl1-preview.png", full: "wham-girl1.png", name: { left: 889, top: 334, startSize: 30, minSize: 25, maxSize: 30, fontFamily: "Anton", fontWeight: "normal", color: "#ffffff", canChangeSize: true, canChangeColor: false, canMove: false, canRotate: false, isCurved: true, curveRadius: 150, tiltAngle: 0, label: "Name", maxChars: 12 }, age: { left: 889, top: 392, startSize: 68, minSize: 68, maxSize: 70, fontFamily: "Anton", fontWeight: "normal", color: "#ffffff", canChangeSize: true, canChangeColor: true, label: "Shirt", maxChars: 2, numericOnly: true, lettersOnly: false, forceUppercase: false, defaultText: "10" } },
  "wham-girl2": { title: "West Ham Girl 2", description: "A beautifully designed \"West Ham Girl 2\" card, ready to personalise.", categories: ["sports", "football", "wsl", "westhamw"], price: "£3.49", preview: "wham-girl2-preview.png", full: "wham-girl2.png", name: { left: 889, top: 339, startSize: 30, minSize: 25, maxSize: 30, fontFamily: "Anton", fontWeight: "normal", color: "#ffffff", canChangeSize: true, canChangeColor: false, canMove: false, canRotate: false, isCurved: true, curveRadius: 150, tiltAngle: 0, label: "Name", maxChars: 12 }, age: { left: 889, top: 395, startSize: 68, minSize: 68, maxSize: 70, fontFamily: "Anton", fontWeight: "normal", color: "#ffffff", canChangeSize: true, canChangeColor: true, label: "Shirt", maxChars: 2, numericOnly: true, lettersOnly: false, forceUppercase: false, defaultText: "10" } },
  "wham-girl3": { title: "West Ham Girl 3", description: "A beautifully designed \"West Ham Girl 3\" card, ready to personalise.", categories: ["sports", "football", "wsl", "westhamw"], price: "£3.49", preview: "wham-girl3-preview.png", full: "wham-girl3.png", name: { left: 889, top: 339, startSize: 30, minSize: 25, maxSize: 30, fontFamily: "Anton", fontWeight: "normal", color: "#ffffff", canChangeSize: true, canChangeColor: false, canMove: false, canRotate: false, isCurved: true, curveRadius: 150, tiltAngle: 0, label: "Name", maxChars: 12 }, age: { left: 889, top: 395, startSize: 68, minSize: 68, maxSize: 70, fontFamily: "Anton", fontWeight: "normal", color: "#ffffff", canChangeSize: true, canChangeColor: true, label: "Shirt", maxChars: 2, numericOnly: true, lettersOnly: false, forceUppercase: false, defaultText: "10" } },
  "wham-girl4": { title: "West Ham Girl 4", description: "A beautifully designed \"West Ham Girl 4\" card, ready to personalise.", categories: ["sports", "football", "wsl", "westhamw"], price: "£3.49", preview: "wham-girl4-preview.png", full: "wham-girl4.png", name: { left: 889, top: 339, startSize: 30, minSize: 25, maxSize: 30, fontFamily: "Anton", fontWeight: "normal", color: "#ffffff", canChangeSize: true, canChangeColor: false, canMove: false, canRotate: false, isCurved: true, curveRadius: 150, tiltAngle: 0, label: "Name", maxChars: 12 }, age: { left: 889, top: 395, startSize: 68, minSize: 68, maxSize: 70, fontFamily: "Anton", fontWeight: "normal", color: "#ffffff", canChangeSize: true, canChangeColor: true, label: "Shirt", maxChars: 2, numericOnly: true, lettersOnly: false, forceUppercase: false, defaultText: "10" } },

  "munited-girl1": { title: "Man United Girl 1", description: "A beautifully designed \"Man United Girl 1\" card, ready to personalise.", categories: ["sports", "football", "wsl", "man-utdw"], price: "£3.49", preview: "munited-girl1-preview.png", full: "munited-girl1.png", name: { left: 885, top: 550, startSize: 40, minSize: 30, maxSize: 45, fontFamily: "Anton", fontWeight: "normal", color: "#001130", canChangeSize: true, canChangeColor: false, canMove: false, canRotate: false, isCurved: true, curveRadius: 150, tiltAngle: 0, label: "Name", maxChars: 12 }, age: { left: 885, top: 635, startSize: 90, minSize: 20, maxSize: 120, fontFamily: "Anton", fontWeight: "normal", color: "#001130", canChangeSize: true, canChangeColor: true, label: "Shirt", maxChars: 2, numericOnly: true, lettersOnly: false, forceUppercase: false, defaultText: "10" } },
  "munited-girl2": { title: "Man United Girl 2", description: "A beautifully designed \"Man United Girl 2\" card, ready to personalise.", categories: ["sports", "football", "wsl", "man-utdw"], price: "£3.49", preview: "munited-girl2-preview.png", full: "munited-girl2.png", name: { left: 885, top: 550, startSize: 40, minSize: 30, maxSize: 45, fontFamily: "Anton", fontWeight: "normal", color: "#001130", canChangeSize: true, canChangeColor: false, canMove: false, canRotate: false, isCurved: true, curveRadius: 150, tiltAngle: 0, label: "Name", maxChars: 12 }, age: { left: 885, top: 675, startSize: 90, minSize: 20, maxSize: 120, fontFamily: "Anton", fontWeight: "normal", color: "#001130", canChangeSize: true, canChangeColor: true, label: "Shirt", maxChars: 2, numericOnly: true, lettersOnly: false, forceUppercase: false, defaultText: "10" } },
  "munited-girl3": { title: "Man United Girl 3", description: "A beautifully designed \"Man United Girl 3\" card, ready to personalise.", categories: ["sports", "football", "wsl", "man-utdw"], price: "£3.49", preview: "munited-girl3-preview.png", full: "munited-girl2.png", name: { left: 885, top: 550, startSize: 40, minSize: 30, maxSize: 45, fontFamily: "Anton", fontWeight: "normal", color: "#001130", canChangeSize: true, canChangeColor: false, canMove: false, canRotate: false, isCurved: true, curveRadius: 150, tiltAngle: 0, label: "Name", maxChars: 12 }, age: { left: 885, top: 675, startSize: 90, minSize: 20, maxSize: 120, fontFamily: "Anton", fontWeight: "normal", color: "#001130", canChangeSize: true, canChangeColor: true, label: "Shirt", maxChars: 2, numericOnly: true, lettersOnly: false, forceUppercase: false, defaultText: "10" } },
  "munited-girl4": { title: "Man United Girl 4", description: "A beautifully designed \"Man United Girl 4\" card, ready to personalise.", categories: ["sports", "football", "wsl", "man-utdw"], price: "£3.49", preview: "munited-girl4-preview.png", full: "munited-girl4.png", name: { left: 885, top: 550, startSize: 40, minSize: 30, maxSize: 45, fontFamily: "Anton", fontWeight: "normal", color: "#001130", canChangeSize: true, canChangeColor: false, canMove: false, canRotate: false, isCurved: true, curveRadius: 150, tiltAngle: 0, label: "Name", maxChars: 12 }, age: { left: 885, top: 675, startSize: 90, minSize: 20, maxSize: 120, fontFamily: "Anton", fontWeight: "normal", color: "#001130", canChangeSize: true, canChangeColor: true, label: "Shirt", maxChars: 2, numericOnly: true, lettersOnly: false, forceUppercase: false, defaultText: "10" } },
  
  "spurs-girl1": { title: "Spurs Girl Card", description: "A beautifully designed \"Spurs Girl Card\" card, ready to personalise.", categories: ["sports", "football", "wsl", "tottenham"], price: "£3.49", preview: "spurs-girl1-preview.png", full: "spurs-girl1.png", name: { left: 913, top: 375, startSize: 26, minSize: 20, maxSize: 34, fontFamily: "Anton", fontWeight: "normal", color: "#12244F", canChangeSize: true, canChangeColor: false, canMove: false, canRotate: false, isCurved: true, curveRadius: 150, tiltAngle: -1, label: "Name", maxChars: 12 }, age: { left: 913, top: 430, startSize: 60, minSize: 20, maxSize: 120, fontFamily: "Anton", fontWeight: "normal", color: "#12244F", canChangeSize: true, canChangeColor: true, tiltAngle: -1, label: "Shirt", maxChars: 2, numericOnly: true, lettersOnly: false, forceUppercase: false, defaultText: "10" } },
  "spurs-girl2": { title: "Spurs Girl Card", description: "A beautifully designed \"Spurs Girl Card\" card, ready to personalise.", categories: ["sports", "football", "wsl", "tottenham"], price: "£3.49", preview: "spurs-girl2-preview.png", full: "spurs-girl2.png", name: { left: 913, top: 375, startSize: 26, minSize: 20, maxSize: 34, fontFamily: "Anton", fontWeight: "normal", color: "#12244F", canChangeSize: true, canChangeColor: false, canMove: false, canRotate: false, isCurved: true, curveRadius: 150, tiltAngle: -1, label: "Name", maxChars: 12 }, age: { left: 913, top: 430, startSize: 60, minSize: 20, maxSize: 120, fontFamily: "Anton", fontWeight: "normal", color: "#12244F", canChangeSize: true, canChangeColor: true, tiltAngle: -1, label: "Shirt", maxChars: 2, numericOnly: true, lettersOnly: false, forceUppercase: false, defaultText: "10" } },
  "spurs-girl3": { title: "Spurs Girl Card", description: "A beautifully designed \"Spurs Girl Card\" card, ready to personalise.", categories: ["sports", "football", "wsl", "tottenham"], price: "£3.49", preview: "spurs-girl3-preview.png", full: "spurs-girl3.png", name: { left: 913, top: 375, startSize: 26, minSize: 20, maxSize: 34, fontFamily: "Anton", fontWeight: "normal", color: "#12244F", canChangeSize: true, canChangeColor: false, canMove: false, canRotate: false, isCurved: true, curveRadius: 150, tiltAngle: -1, label: "Name", maxChars: 12 }, age: { left: 913, top: 430, startSize: 60, minSize: 20, maxSize: 120, fontFamily: "Anton", fontWeight: "normal", color: "#12244F", canChangeSize: true, canChangeColor: true, tiltAngle: -1, label: "Shirt", maxChars: 2, numericOnly: true, lettersOnly: false, forceUppercase: false, defaultText: "10" } },
  "spurs-girl4": { title: "Spurs Girl Card", description: "A beautifully designed \"Spurs Girl Card\" card, ready to personalise.", categories: ["sports", "football", "wsl", "tottenham"], price: "£3.49", preview: "spurs-girl-4-preview.png", full: "spurs-girl4.png", name: { left: 913, top: 375, startSize: 26, minSize: 20, maxSize: 34, fontFamily: "Anton", fontWeight: "normal", color: "#12244F", canChangeSize: true, canChangeColor: false, canMove: false, canRotate: false, isCurved: true, curveRadius: 150, tiltAngle: -1, label: "Name", maxChars: 12 }, age: { left: 913, top: 430, startSize: 60, minSize: 20, maxSize: 120, fontFamily: "Anton", fontWeight: "normal", color: "#12244F", canChangeSize: true, canChangeColor: true, tiltAngle: -1, label: "Shirt", maxChars: 2, numericOnly: true, lettersOnly: false, forceUppercase: false, defaultText: "10" } },
  
  "spurs-ladies-celebrating": { title: "Spurs Ladies Celebrating Card", description: "A celebration card for Tottenham fans.", categories: ["sports", "football", "wsl", "tottenham"], preview: "spurs-ladies-celebrating-preview.png", full: "spurs-ladies-celebrating.png" },

  "brighton-celebrating": { title: "Brighton Celebrating Card", description: "A celebration card for Brighton fans.", categories: ["sports", "football", "wsl", "brighton"], preview: "brighton-celebrating-preview.png", full: "brighton-celebrating.png" },
  
  "brighton-girl1": { title: "Brighton Girl Card", description: "A beautifully designed \"Brighton Girl Card\" card, ready to personalise.", categories: ["sports", "football", "wsl", "brighton"], price: "£3.49", preview: "brighton-girl1-preview.png", full: "brighton-girl1.png", name: { left: 890, top: 470, startSize: 26, minSize: 20, maxSize: 30, fontFamily: "Anton", fontWeight: "normal", color: "#FFFFFF", canChangeSize: true, canChangeColor: false, canMove: false, canRotate: false, isCurved: true, curveRadius: 150, tiltAngle: 0, label: "Name", maxChars: 12 }, age: { left: 890, top: 525, startSize: 70, minSize: 20, maxSize: 120, fontFamily: "Anton", fontWeight: "normal", color: "#FFFFFF", canChangeSize: true, canChangeColor: true, label: "Shirt", maxChars: 2, numericOnly: true, lettersOnly: false, forceUppercase: false, defaultText: "10" } },
  "brighton-girl2": { title: "Brighton Girl Card", description: "A beautifully designed \"Brighton Girl Card\" card, ready to personalise.", categories: ["sports", "football", "wsl", "brighton"], price: "£3.49", preview: "brighton-girl2-preview.png", full: "brighton-girl2.png", name: { left: 890, top: 470, startSize: 26, minSize: 20, maxSize: 30, fontFamily: "Anton", fontWeight: "normal", color: "#FFFFFF", canChangeSize: true, canChangeColor: false, canMove: false, canRotate: false, isCurved: true, curveRadius: 150, tiltAngle: 0, label: "Name", maxChars: 12 }, age: { left: 890, top: 525, startSize: 70, minSize: 20, maxSize: 120, fontFamily: "Anton", fontWeight: "normal", color: "#FFFFFF", canChangeSize: true, canChangeColor: true, label: "Shirt", maxChars: 2, numericOnly: true, lettersOnly: false, forceUppercase: false, defaultText: "10" } },
  "brighton-girl3": { title: "Brighton Girl Card", description: "A beautifully designed \"Brighton Girl Card\" card, ready to personalise.", categories: ["sports", "football", "wsl", "brighton"], price: "£3.49", preview: "brighton-girl3-preview.png", full: "brighton-girl3.png", name: { left: 890, top: 470, startSize: 26, minSize: 20, maxSize: 30, fontFamily: "Anton", fontWeight: "normal", color: "#FFFFFF", canChangeSize: true, canChangeColor: false, canMove: false, canRotate: false, isCurved: true, curveRadius: 150, tiltAngle: 0, label: "Name", maxChars: 12 }, age: { left: 890, top: 525, startSize: 70, minSize: 20, maxSize: 120, fontFamily: "Anton", fontWeight: "normal", color: "#FFFFFF", canChangeSize: true, canChangeColor: true, label: "Shirt", maxChars: 2, numericOnly: true, lettersOnly: false, forceUppercase: false, defaultText: "10" } },
  "brighton-girl4": { title: "Brighton Girl Card", description: "A beautifully designed \"Brighton Girl Card\" card, ready to personalise.", categories: ["sports", "football", "wsl", "brighton"], price: "£3.49", preview: "brighton-girl4-preview.png", full: "brighton-girl4.png", name: { left: 890, top: 470, startSize: 26, minSize: 20, maxSize: 30, fontFamily: "Anton", fontWeight: "normal", color: "#FFFFFF", canChangeSize: true, canChangeColor: false, canMove: false, canRotate: false, isCurved: true, curveRadius: 150, tiltAngle: 0, label: "Name", maxChars: 12 }, age: { left: 890, top: 525, startSize: 70, minSize: 20, maxSize: 120, fontFamily: "Anton", fontWeight: "normal", color: "#FFFFFF", canChangeSize: true, canChangeColor: true, label: "Shirt", maxChars: 2, numericOnly: true, lettersOnly: false, forceUppercase: false, defaultText: "10" } },
  
  "cfc-shirt-blues1": { title: "Chelsea Blues Shirt Card", description: "A personalised Chelsea shirt card - add their name and squad number to the back of the shirt.", categories: ["sports", "football", "premiership", "chelsea"], price: "£3.49", preview: "cfc-shirt-blues1-preview.png", full: "cfc-shirt-blues1.png", name: { left: 885, top: 535, startSize: 30, minSize: 20, maxSize: 34, fontFamily: "Anton", fontWeight: "normal", color: "#FFFFFF", canChangeSize: false, canChangeColor: false, canMove: false, canRotate: false, isCurved: true, curveRadius: 150, tiltAngle: 0, label: "Name", maxChars: 7 }, age: { left: 885, top: 600, startSize: 70, minSize: 20, maxSize: 120, fontFamily: "Anton", fontWeight: "normal", color: "#FFFFFF", canChangeSize: false, canChangeColor: true, label: "Shirt", maxChars: 2, numericOnly: true, lettersOnly: false, forceUppercase: false, defaultText: "10" } },
  "cfc-shirt-blues2": { title: "Chelsea Blues Shirt Card", description: "A personalised Chelsea shirt card - add their name and squad number to the back of the shirt.", categories: ["sports", "football", "premiership", "chelsea"], price: "£3.49", preview: "cfc-shirt-blues2-preview.png", full: "cfc-shirt-blues2.png", name: { left: 885, top: 535, startSize: 30, minSize: 20, maxSize: 34, fontFamily: "Anton", fontWeight: "normal", color: "#FFFFFF", canChangeSize: false, canChangeColor: false, canMove: false, canRotate: false, isCurved: true, curveRadius: 150, tiltAngle: 0, label: "Name", maxChars: 7 }, age: { left: 885, top: 600, startSize: 70, minSize: 20, maxSize: 120, fontFamily: "Anton", fontWeight: "normal", color: "#FFFFFF", canChangeSize: false, canChangeColor: true, label: "Shirt", maxChars: 2, numericOnly: true, lettersOnly: false, forceUppercase: false, defaultText: "10" } },
  
  "dancing-queen": { title: "Dancing Queen Card", description: "A fun, colourful birthday card for someone who loves to dance.", categories: ["all", "birthdays", "children", "for-her"], preview: "dancing-queen-preview.png", full: "dancing-queen.png" },
 
  "netball-navy-girl1": { title: "Netball Girl Navy Outfit Girl 1", description: "A personalised netball card with a girl wearing a navy kit where you can add her name and squad letters to the shirt.", categories: ["sports", "netball"], price: "£3.49", preview: "netball-navy-girl1-preview.png", full: "netball-navyblue-girl1.png", name: { left: 885, top: 295, startSize: 80, minSize: 50, maxSize: 57, fontFamily: "Anton", fontWeight: "normal", color: "#FFFFFF", canChangeSize: false, canChangeColor: false, canMove: false, canRotate: false, isCurved: false, curveRadius: 480, tiltAngle: 0, label: "Name", maxChars: 10 }, age: { left: 847, top: 593, startSize: 65, minSize: 20, maxSize: 120, fontFamily: "Anton", fontWeight: "normal", color: "#FFFFFF", canChangeSize: false, canChangeColor: true, label: "Shirt", maxChars: 2, numericOnly: false, lettersOnly: true, forceUppercase: true, defaultText: "GA" } }, 
  "netball-navy-girl2": { title: "Netball Girl Navy Outfit Girl 2", description: "A personalised netball card with a girl wearing a navy kit where you can add her name and squad letters to the shirt.", categories: ["sports", "netball"], price: "£3.49", preview: "netball-navy-girl2-preview.png", full: "netball-navyblue-girl2.png", name: { left: 887, top: 296, startSize: 80, minSize: 50, maxSize: 57, fontFamily: "Anton", fontWeight: "normal", color: "#FFFFFF", canChangeSize: false, canChangeColor: false, canMove: false, canRotate: false, isCurved: false, curveRadius: 480, tiltAngle: 0, label: "Name", maxChars: 10 }, age: { left: 845, top: 593, startSize: 65, minSize: 20, maxSize: 120, fontFamily: "Anton", fontWeight: "normal", color: "#FFFFFF", canChangeSize: false, canChangeColor: true, label: "Shirt", maxChars: 2, numericOnly: false, lettersOnly: true, forceUppercase: true, defaultText: "GA" } }, 
  "netball-navy-girl3": { title: "Netball Girl Navy Outfit Girl 3", description: "A personalised netball card with a girl wearing a navy kit where you can add her name and squad letters to the shirt.", categories: ["sports", "netball"], price: "£3.49", preview: "netball-navy-girl3-preview.png", full: "netball-navyblue-girl3.png", name: { left: 894, top: 295, startSize: 80, minSize: 50, maxSize: 57, fontFamily: "Anton", fontWeight: "normal", color: "#FFFFFF", canChangeSize: false, canChangeColor: false, canMove: false, canRotate: false, isCurved: false, curveRadius: 480, tiltAngle: 0, label: "Name", maxChars: 10 }, age: { left: 850, top: 593, startSize: 65, minSize: 20, maxSize: 120, fontFamily: "Anton", fontWeight: "normal", color: "#FFFFFF", canChangeSize: false, canChangeColor: true, label: "Shirt", maxChars: 2, numericOnly: false, lettersOnly: true, forceUppercase: true, defaultText: "GA" } }, 
  "netball-navy-girl4": { title: "Netball Girl Navy Outfit Girl 4", description: "A personalised netball card with a girl wearing a navy kit where you can add her name and squad letters to the shirt.", categories: ["sports", "netball"], price: "£3.49", preview: "netball-navy-girl4-preview.png", full: "netball-navyblue-girl4.png", name: { left: 883, top: 295, startSize: 80, minSize: 50, maxSize: 57, fontFamily: "Anton", fontWeight: "normal", color: "#FFFFFF", canChangeSize: false, canChangeColor: false, canMove: false, canRotate: false, isCurved: false, curveRadius: 480, tiltAngle: 0, label: "Name", maxChars: 10 }, age: { left: 840, top: 593, startSize: 65, minSize: 20, maxSize: 120, fontFamily: "Anton", fontWeight: "normal", color: "#FFFFFF", canChangeSize: false, canChangeColor: true, label: "Shirt", maxChars: 2, numericOnly: false, lettersOnly: true, forceUppercase: true, defaultText: "GA" } },

  "netball-green-girl1": { title: "Netball Girl Green Outfit Girl 1", description: "A personalised netball card with a girl wearing a green kit where you can add her name and squad letters to the shirt.", categories: ["sports", "netball"], price: "£3.49", preview: "netball-green-girl1-preview.png", full: "netball-green-girl1.png", name: { left: 894, top: 294, startSize: 80, minSize: 50, maxSize: 57, fontFamily: "Anton", fontWeight: "normal", color: "#FFFFFF", canChangeSize: false, canChangeColor: false, canMove: false, canRotate: false, isCurved: false, curveRadius: 480, tiltAngle: 0, label: "Name", maxChars: 10 }, age: { left: 850, top: 594, startSize: 65, minSize: 20, maxSize: 120, fontFamily: "Anton", fontWeight: "normal", color: "#FFFFFF", canChangeSize: false, canChangeColor: true, label: "Shirt", maxChars: 2, numericOnly: false, lettersOnly: true, forceUppercase: true, defaultText: "GA" } }, 
  "netball-green-girl2": { title: "Netball Girl Green Outfit Girl 2", description: "A personalised netball card with a girl wearing a green kit where you can add her name and squad letters to the shirt.", categories: ["sports", "netball"], price: "£3.49", preview: "netball-green-girl2-preview.png", full: "netball-green-girl2.png", name: { left: 894, top: 295, startSize: 80, minSize: 50, maxSize: 57, fontFamily: "Anton", fontWeight: "normal", color: "#FFFFFF", canChangeSize: false, canChangeColor: false, canMove: false, canRotate: false, isCurved: false, curveRadius: 480, tiltAngle: 0, label: "Name", maxChars: 10 }, age: { left: 849, top: 593, startSize: 65, minSize: 20, maxSize: 120, fontFamily: "Anton", fontWeight: "normal", color: "#FFFFFF", canChangeSize: false, canChangeColor: true, label: "Shirt", maxChars: 2, numericOnly: false, lettersOnly: true, forceUppercase: true, defaultText: "GA" } }, 
  "netball-green-girl3": { title: "Netball Girl Green Outfit Girl 3", description: "A personalised netball card with a girl wearing a green kit where you can add her name and squad letters to the shirt.", categories: ["sports", "netball"], price: "£3.49", preview: "netball-green-girl3-preview.png", full: "netball-green-girl3.png", name: { left: 888, top: 295, startSize: 80, minSize: 50, maxSize: 57, fontFamily: "Anton", fontWeight: "normal", color: "#FFFFFF", canChangeSize: false, canChangeColor: false, canMove: false, canRotate: false, isCurved: false, curveRadius: 480, tiltAngle: 0, label: "Name", maxChars: 10 }, age: { left: 844, top: 593, startSize: 65, minSize: 20, maxSize: 120, fontFamily: "Anton", fontWeight: "normal", color: "#FFFFFF", canChangeSize: false, canChangeColor: true, label: "Shirt", maxChars: 2, numericOnly: false, lettersOnly: true, forceUppercase: true, defaultText: "GA" } }, 
  "netball-green-girl4": { title: "Netball Girl Green Outfit Girl 4", description: "A personalised netball card with a girl wearing a green kit where you can add her name and squad letters to the shirt.", categories: ["sports", "netball"], price: "£3.49", preview: "netball-green-girl4-preview.png", full: "netball-green-girl4.png", name: { left: 891, top: 295, startSize: 80, minSize: 50, maxSize: 57, fontFamily: "Anton", fontWeight: "normal", color: "#FFFFFF", canChangeSize: false, canChangeColor: false, canMove: false, canRotate: false, isCurved: false, curveRadius: 480, tiltAngle: 0, label: "Name", maxChars: 10 }, age: { left: 847, top: 593, startSize: 65, minSize: 20, maxSize: 120, fontFamily: "Anton", fontWeight: "normal", color: "#FFFFFF", canChangeSize: false, canChangeColor: true, label: "Shirt", maxChars: 2, numericOnly: false, lettersOnly: true, forceUppercase: true, defaultText: "GA" } },

  "netball-red-girl1": { title: "Netball Girl Red Outfit Girl 1", description: "A personalised netball card with a girl wearing a red kit where you can add her name and squad letters to the shirt.", categories: ["sports", "netball"], price: "£3.49", preview: "netball-red-girl1-preview.png", full: "netball-red-girl1.png", name: { left: 886, top: 292, startSize: 80, minSize: 50, maxSize: 57, fontFamily: "Anton", fontWeight: "normal", color: "#FFFFFF", canChangeSize: false, canChangeColor: false, canMove: false, canRotate: false, isCurved: false, curveRadius: 480, tiltAngle: 0, label: "Name", maxChars: 10 }, age: { left: 844, top: 593, startSize: 65, minSize: 20, maxSize: 120, fontFamily: "Anton", fontWeight: "normal", color: "#FFFFFF", canChangeSize: false, canChangeColor: true, label: "Shirt", maxChars: 2, numericOnly: false, lettersOnly: true, forceUppercase: true, defaultText: "GA" } }, 
  "netball-red-girl2": { title: "Netball Girl Red Outfit Girl 2", description: "A personalised netball card with a girl wearing a red kit where you can add her name and squad letters to the shirt.", categories: ["sports", "netball"], price: "£3.49", preview: "netball-red-girl2-preview.png", full: "netball-red-girl2.png", name: { left: 881, top: 293, startSize: 80, minSize: 50, maxSize: 57, fontFamily: "Anton", fontWeight: "normal", color: "#FFFFFF", canChangeSize: false, canChangeColor: false, canMove: false, canRotate: false, isCurved: false, curveRadius: 480, tiltAngle: 0, label: "Name", maxChars: 10 }, age: { left: 840, top: 593, startSize: 65, minSize: 20, maxSize: 120, fontFamily: "Anton", fontWeight: "normal", color: "#FFFFFF", canChangeSize: false, canChangeColor: true, label: "Shirt", maxChars: 2, numericOnly: false, lettersOnly: true, forceUppercase: true, defaultText: "GA" } }, 
  "netball-red-girl3": { title: "Netball Girl Red Outfit Girl 3", description: "A personalised netball card with a girl wearing a red kit where you can add her name and squad letters to the shirt.", categories: ["sports", "netball"], price: "£3.49", preview: "netball-red-girl3-preview.png", full: "netball-red-girl3.png", name: { left: 881, top: 296, startSize: 80, minSize: 50, maxSize: 57, fontFamily: "Anton", fontWeight: "normal", color: "#FFFFFF", canChangeSize: false, canChangeColor: false, canMove: false, canRotate: false, isCurved: false, curveRadius: 480, tiltAngle: 0, label: "Name", maxChars: 10 }, age: { left: 840, top: 593, startSize: 65, minSize: 20, maxSize: 120, fontFamily: "Anton", fontWeight: "normal", color: "#FFFFFF", canChangeSize: false, canChangeColor: true, label: "Shirt", maxChars: 2, numericOnly: false, lettersOnly: true, forceUppercase: true, defaultText: "GA" } }, 
  "netball-red-girl4": { title: "Netball Girl Red Outfit Girl 4", description: "A personalised netball card with a girl wearing a red kit where you can add her name and squad letters to the shirt.", categories: ["sports", "netball"], price: "£3.49", preview: "netball-red-girl4-preview.png", full: "netball-red-girl4.png", name: { left: 878, top: 301, startSize: 80, minSize: 50, maxSize: 57, fontFamily: "Anton", fontWeight: "normal", color: "#FFFFFF", canChangeSize: false, canChangeColor: false, canMove: false, canRotate: false, isCurved: false, curveRadius: 480, tiltAngle: 0, label: "Name", maxChars: 10 }, age: { left: 839, top: 593, startSize: 65, minSize: 20, maxSize: 120, fontFamily: "Anton", fontWeight: "normal", color: "#FFFFFF", canChangeSize: false, canChangeColor: true, label: "Shirt", maxChars: 2, numericOnly: false, lettersOnly: true, forceUppercase: true, defaultText: "GA" } },
                        
  "topboy-whu": { title: "Topboy West Ham United Card", description: "A card for die-hard West Ham fans.", categories: ["for-him", "sports", "football", "championship", "west-ham"], preview: "topboy-whu-preview.png", full: "topboy-whu.png" },
  
  "tot-shirt1": { title: "Tottenham Shirt Card", description: "A personalised Tottenham shirt card - add their name and squad number to the back of the shirt.", categories: ["sports", "football", "premiership", "tottenham"], price: "£3.49", preview: "tot-shirt-preview.png", full: "tot-shirt.png", name: { left: 883, top: 550, startSize: 40, minSize: 30, maxSize: 45, fontFamily: "Anton", fontWeight: "normal", color: "#001130", canChangeSize: true, canChangeColor: false, canMove: false, canRotate: false, isCurved: true, curveRadius: 150, tiltAngle: 0, label: "Name", maxChars: 12 }, age: { left: 883, top: 635, startSize: 90, minSize: 20, maxSize: 120, fontFamily: "Anton", fontWeight: "normal", color: "#001130", canChangeSize: true, canChangeColor: true, label: "Shirt", maxChars: 2, numericOnly: true, lettersOnly: false, forceUppercase: false, defaultText: "10" } },
  "tot-shirt2": { title: "Tottenham Shirt Card", description: "A personalised Tottenham shirt card - add their name and squad number to the back of the shirt.", categories: ["sports", "football", "premiership", "tottenham"], price: "£3.49", preview: "tot-shirt2-preview.png", full: "tot-shirt2.png", name: { left: 883, top: 550, startSize: 40, minSize: 30, maxSize: 45, fontFamily: "Anton", fontWeight: "normal", color: "#001130", canChangeSize: true, canChangeColor: false, canMove: false, canRotate: false, isCurved: true, curveRadius: 150, tiltAngle: 0, label: "Name", maxChars: 12 }, age: { left: 883, top: 635, startSize: 90, minSize: 20, maxSize: 120, fontFamily: "Anton", fontWeight: "normal", color: "#001130", canChangeSize: true, canChangeColor: true, label: "Shirt", maxChars: 2, numericOnly: true, lettersOnly: false, forceUppercase: false, defaultText: "10" } },
  "tot-shirt3": { title: "Tottenham Shirt Card", description: "A personalised Tottenham shirt card - add their name and squad number to the back of the shirt.", categories: ["sports", "football", "premiership", "tottenham"], price: "£3.49", preview: "tot-shirt3-preview.png", full: "tot-shirt3.png", name: { left: 883, top: 550, startSize: 40, minSize: 30, maxSize: 45, fontFamily: "Anton", fontWeight: "normal", color: "#001130", canChangeSize: true, canChangeColor: false, canMove: false, canRotate: false, isCurved: true, curveRadius: 150, tiltAngle: 0, label: "Name", maxChars: 12 }, age: { left: 883, top: 635, startSize: 90, minSize: 20, maxSize: 120, fontFamily: "Anton", fontWeight: "normal", color: "#001130", canChangeSize: true, canChangeColor: true, label: "Shirt", maxChars: 2, numericOnly: true, lettersOnly: false, forceUppercase: false, defaultText: "10" } },
  "tot-shirt4": { title: "Tottenham Shirt Card", description: "A personalised Tottenham shirt card - add their name and squad number to the back of the shirt.", categories: ["sports", "football", "premiership", "tottenham"], price: "£3.49", preview: "tot-shirt4-preview.png", full: "tot-shirt4.png", name: { left: 883, top: 550, startSize: 40, minSize: 30, maxSize: 45, fontFamily: "Anton", fontWeight: "normal", color: "#001130", canChangeSize: true, canChangeColor: false, canMove: false, canRotate: false, isCurved: true, curveRadius: 150, tiltAngle: 0, label: "Name", maxChars: 12 }, age: { left: 883, top: 635, startSize: 90, minSize: 20, maxSize: 120, fontFamily: "Anton", fontWeight: "normal", color: "#001130", canChangeSize: true, canChangeColor: true, label: "Shirt", maxChars: 2, numericOnly: true, lettersOnly: false, forceUppercase: false, defaultText: "10" } },

  "topboy-mfc": { title: "Topboy Millwall FC Card", description: "A card for die-hard Millwall fans.", categories: ["for-him", "sports", "football", "championship", "millwall"], preview: "topboy-mfc-preview.png", full: "topboy-mfc.png" },

  "golfmasters": { title: "Golf Masters", description: "A golf-themed card for the golfer in your life - add their name to make it personal.", categories: ["sports", "for-him", "golf"], preview: "golfmasters-preview.png", full: "golfmasters.png", name: { left: 894, top: 250, startSize: 70, minSize: 70, maxSize: 70, fontFamily: "Anton", fontWeight: "normal", color: "#f5b33a", canChangeSize: false, canChangeColor: false, canMove: false, canRotate: false, isCurved: false, curveRadius: 470, tiltAngle: 0, label: "Name", maxChars: 10 } },
  "golfpro": { title: "Golf Pro", description: "A golf-themed card for the golfer in your life - add their name to make it personal.", categories: ["sports", "for-him", "golf"], preview: "golfpro-preview.png", full: "golfpro.png", name: { left: 897, top: 286, startSize: 40, minSize: 30, maxSize: 40, fontFamily: "Anton", fontWeight: "normal", color: "#204420", canChangeSize: false, canChangeColor: false, canMove: false, canRotate: false, isCurved: true, curveRadius: 500, tiltAngle: 0, label: "Name", maxChars: 9 } },

  "golfer": { title: "Golfer", description: "A golf-themed card for the golfer in your life - add their name to make it personal.", categories: ["all", "sports", "for-him", "golf", "birthdays"], preview: "golfer-preview.png", full: "golfer.png", name: { left: 894, top: 312, startSize: 72, minSize: 68, maxSize: 70, fontFamily: "Anton", fontWeight: "normal", color: "#0f214b", canChangeSize: false, canChangeColor: false, canMove: false, canRotate: false, isCurved: false, curveRadius: 700, tiltAngle: 0, label: "Name", maxChars: 9 } },
  
  "liv-ladies-celebrating": { title: "Liverpool Ladies Celebrating Card", description: "A celebration card for Liverpool fans.", categories: ["sports", "football", "wsl", "liverpool"], preview: "liv-ladies-celebrating-preview.png", full: "liv-ladies-celebrating.png" },
  
  "charltonfan": { title: "Charlton Fan", description: "A beautifully designed \"Millwall Christmas Card\" card, ready to personalise.", categories: ["sports", "football", "championship", "charlton"], preview: "charltonfan-preview.png", full: "charltonfan.png" },
  "qprfan": { title: "QPR Fan", description: "A beautifully designed \"Millwall Christmas Card\" card, ready to personalise.", categories: ["sports", "football", "championship", "qpr"], preview: "qprfan-preview.png", full: "qprfan.png" },
  "wrexhamfan": { title: "Wrexham Fan", description: "A beautifully designed \"Millwall Christmas Card\" card, ready to personalise.", categories: ["sports", "football", "championship", "wrexham"], preview: "wrexhamrfan-preview.png", full: "wrexhamrfan.png" },

  "cardiff-fan": { title: "Cardiff City Fan", description: "A beautifully designed \"Millwall Christmas Card\" card, ready to personalise.", categories: ["sports", "football", "championship", "cardiff"], preview: "cardiff-fan-preview.png", full: "cardiff-fan.png" },
  "norwich-fan": { title: "Norwich City Fan", description: "A beautifully designed \"Millwall Christmas Card\" card, ready to personalise.", categories: ["sports", "football", "championship", "norwich"], preview: "norwich-fan-preview.png", full: "norwich-fan.png" },
  "middlesbrough-lion": { title: "Middlesbrough Lion", description: "A beautifully designed \"Millwall Christmas Card\" card, ready to personalise.", categories: ["sports", "football", "championship", "middlesbrough"], preview: "middlesbrough-lion-preview.png", full: "middlesbrough-lion.png" },


  
  "mfc-christmas": { title: "Millwall Christmas Card", description: "A beautifully designed \"Millwall Christmas Card\" card, ready to personalise.", categories: ["sports", "football", "championship", "millwall"], preview: "mfc-christmas-preview.png", full: "mfc-christmas.png" },
  
  "mfc-shirt1": { title: "Millwall Boy 1", description: "A personalised Millwall shirt card - add their name and squad number to the back of the shirt.", categories: ["sports", "football", "championship", "millwall"], price: "£3.49", preview: "mfc-shirt1-preview.png", full: "mfc-shirt1.png", name: { left: 885, top: 550, startSize: 40, minSize: 30, maxSize: 45, fontFamily: "Anton", fontWeight: "normal", color: "#FFFFFF", canChangeSize: true, canChangeColor: false, canMove: false, canRotate: false, isCurved: true, curveRadius: 150, tiltAngle: 0, label: "Name", maxChars: 12 }, age: { left: 885, top: 635, startSize: 90, minSize: 20, maxSize: 120, fontFamily: "Anton", fontWeight: "normal", color: "#FFFFFF", canChangeSize: true, canChangeColor: true, label: "Shirt", maxChars: 2, numericOnly: true, lettersOnly: false, forceUppercase: false, defaultText: "10" } },
  "mfc-shirt2": { title: "Millwall Boy 2", description: "A personalised Millwall shirt card - add their name and squad number to the back of the shirt.", categories: ["sports", "football", "championship", "millwall"], price: "£3.49", preview: "mfc-shirt2-preview.png", full: "mfc-shirt2.png", name: { left: 885, top: 550, startSize: 40, minSize: 30, maxSize: 45, fontFamily: "Anton", fontWeight: "normal", color: "#FFFFFF", canChangeSize: true, canChangeColor: false, canMove: false, canRotate: false, isCurved: true, curveRadius: 150, tiltAngle: 0, label: "Name", maxChars: 12 }, age: { left: 885, top: 635, startSize: 90, minSize: 20, maxSize: 120, fontFamily: "Anton", fontWeight: "normal", color: "#FFFFFF", canChangeSize: true, canChangeColor: true, label: "Shirt", maxChars: 2, numericOnly: true, lettersOnly: false, forceUppercase: false, defaultText: "10" } },
  "mfc-shirt3": { title: "Millwall Boy 3", description: "A personalised Millwall shirt card - add their name and squad number to the back of the shirt.", categories: ["sports", "football", "championship", "millwall"], price: "£3.49", preview: "mfc-shirt3-preview.png", full: "mfc-shirt3.png", name: { left: 885, top: 550, startSize: 40, minSize: 30, maxSize: 45, fontFamily: "Anton", fontWeight: "normal", color: "#FFFFFF", canChangeSize: true, canChangeColor: false, canMove: false, canRotate: false, isCurved: true, curveRadius: 150, tiltAngle: 0, label: "Name", maxChars: 12 }, age: { left: 885, top: 635, startSize: 90, minSize: 20, maxSize: 120, fontFamily: "Anton", fontWeight: "normal", color: "#FFFFFF", canChangeSize: true, canChangeColor: true, label: "Shirt", maxChars: 2, numericOnly: true, lettersOnly: false, forceUppercase: false, defaultText: "10" } },
  "mfc-shirt4": { title: "Millwall Boy 4", description: "A personalised Millwall shirt card - add their name and squad number to the back of the shirt.", categories: ["sports", "football", "championship", "millwall"], price: "£3.49", preview: "mfc-shirt4-preview.png", full: "mfc-shirt4.png", name: { left: 885, top: 550, startSize: 40, minSize: 30, maxSize: 45, fontFamily: "Anton", fontWeight: "normal", color: "#FFFFFF", canChangeSize: true, canChangeColor: false, canMove: false, canRotate: false, isCurved: true, curveRadius: 150, tiltAngle: 0, label: "Name", maxChars: 12 }, age: { left: 885, top: 635, startSize: 90, minSize: 20, maxSize: 120, fontFamily: "Anton", fontWeight: "normal", color: "#FFFFFF", canChangeSize: true, canChangeColor: true, label: "Shirt", maxChars: 2, numericOnly: true, lettersOnly: false, forceUppercase: false, defaultText: "10" } },

  "nolu-lion1": { title: "No One Likes Us Lion Card", description: "A beautifully designed \"No One Likes Us Lion Card\" card, ready to personalise.", categories: ["sports", "football", "championship", "millwall"], preview: "nolu-lion1-preview.png", full: "nolu-lion1.png", name: { left: 890, top: 246, startSize: 75, minSize: 70, maxSize: 78, fontFamily: "Anton", fontWeight: "normal", color: "#FFFFFF", canChangeSize: true, canChangeColor: false, canMove: false, canRotate: false, isCurved: true, curveRadius: 610, tiltAngle: -3, label: "Name", maxChars: 12 } },
  
  "birthday-mfc-photo1": { title: "Lions Birthday", price: "£3.49", description: "A personalised birthday card - add a favourite photo and their name.", categories: ["sports", "football", "championship", "millwall", "photo-upload"], preview: "lions-birthday-preview.png", full: "lions-birthday.png", name: { left: 898, top: 752, startSize: 63, minSize: 60, maxSize: 70, fontFamily: "Anton", fontWeight: "normal", color: "#0F214B", canChangeSize: true, canChangeColor: false, canMove: false, canRotate: false, isCurved: true, curveRadius: 580, tiltAngle: -0, label: "Name", maxChars: 9 },
    photo: { left: 1008, top: 180, width: 310, height: 310 } },
  
  "whu-shirt": { title: "West Ham Shirt Card", description: "A personalised West Ham shirt card - add their name and squad number to the back of the shirt.", categories: ["sports", "football", "championship", "west-ham"], price: "£3.49", preview: "whu-shirt-preview.png", full: "whu-shirt.png", name: { left: 885, top: 550, startSize: 40, minSize: 30, maxSize: 45, fontFamily: "Anton", fontWeight: "normal", color: "#FFFFFF", canChangeSize: true, canChangeColor: false, canMove: false, canRotate: false, isCurved: true, curveRadius: 150, tiltAngle: 0, label: "Name", maxChars: 12 }, age: { left: 885, top: 635, startSize: 90, minSize: 20, maxSize: 120, fontFamily: "Anton", fontWeight: "normal", color: "#FFFFFF", canChangeSize: true, canChangeColor: true, label: "Shirt", maxChars: 2, numericOnly: true, lettersOnly: false, forceUppercase: false, defaultText: "40" } },
  
  "discodarts": { title: "Disco Darts", description: "A darts-themed card for the player who's always aiming for the bullseye - add their name.", categories: ["sports", "for-him", "darts"], preview: "discodarts-preview.png", full: "discodarts.png", name: { left: 894, top: 244, startSize: 43, minSize: 40, maxSize: 43, fontFamily: "Anton", fontWeight: "normal", color: "#001591", canChangeSize: false, canChangeColor: false, canMove: false, canRotate: false, isCurved: true, curveRadius: 500, tiltAngle: 0, label: "Name", maxChars: 9 } },
  "anyoneforcricket": { title: "Anyone for Cricket", description: "A cricket-themed card for the player who lives for the crease - add their name.", categories: ["sports", "for-him", "cricket"], preview: "anyoneforcricket-preview.png", full: "anyoneforcricket.png", name: { left: 900, top: 309, startSize: 38, minSize: 37, maxSize: 40, fontFamily: "Anton", fontWeight: "normal", color: "#01316e", canChangeSize: false, canChangeColor: false, canMove: false, canRotate: false, isCurved: true, curveRadius: 520, tiltAngle: 0, label: "Name", maxChars: 8 } },
  
  "dartschampion": { title: "Darts Champion", description: "A darts-themed card for the player who's always aiming for the bullseye - add their name.", categories: ["sports", "for-him", "darts"], preview: "dartschampion-preview.png", full: "dartschampion.png", name: { left: 894, top: 287, startSize: 83, minSize: 80, maxSize: 85, fontFamily: "Anton", fontWeight: "normal", color: "#FFFFFF", canChangeSize: false, canChangeColor: false, canMove: false, canRotate: false, isCurved: false, curveRadius: 470, tiltAngle: 0, label: "Name", maxChars: 10 } },
  
  "vintagecricket": { title: "Vintage Cricket", description: "A cricket-themed card for the player who lives for the crease - add their name.", categories: ["sports", "for-him", "cricket"], preview: "vintagecricket-preview.png", full: "vintagecricket.png" },
  
  "dartsmasterphoto": { title: "Darts Master", price: "£3.49", description: "A darts-themed card for the player who's always aiming for the bullseye - add their name.", categories: ["sports", "darts", "for-him", "photo-upload"], preview: "dartsmasterphoto-preview.png", full: "dartsmasterphoto.png", 
    photo: { left: 892, top: 525, width: 320, height: 320 } },
  
  
  "5kboy-photo": { title: "5K Achievement Boy", price: "£3.49", description: "Celebrate their 5K running achievement - add a photo, the event name, date and finish time.", categories: ["running"], preview: "5kboy-photo-preview.png", full: "5kboy-photo.png",
    photo: { left: 909.6, top: 331.3, width: 408.1, height: 385.4 },
    extraFields: [
      { key: "event", label: "Event", left: 866, top: 627, fontSize: 17, color: "#D9971D", maxChars: 20 },
      { key: "date", label: "Date", left: 861, top: 678, fontSize: 17, color: "#D9971D", maxChars: 20 },
      { key: "finishTime", label: "Time", left: 900, top: 733, fontSize: 17, color: "#D9971D", maxChars: 12 }
    ] },
  "10kboy-photo": { title: "10K Achievement Boy", price: "£3.49", description: "Celebrate their 10K running achievement - add a photo, the event name, date and finish time.", categories: ["running"], preview: "10krace-boy-preview.png", full: "10krace-boy.png",
    photo: { left: 909.6, top: 331.3, width: 408.1, height: 385.4 },
    extraFields: [
      { key: "event", label: "Event", left: 852, top: 632, fontFamily: "Oswald-VariableFont_wght", fontSize: 25, color: "#001e3f", maxChars: 20 },
      { key: "date", label: "Date", left: 846, top: 703, fontFamily: "Oswald-VariableFont_wght", fontSize: 25, color: "#001e3f", maxChars: 20 },
      { key: "finishTime", label: "Time", left: 895, top: 772, fontFamily: "Oswald-VariableFont_wght", fontSize: 25, color: "#001e3f", maxChars: 18 }
    ] },
  "26mboy-photo": { title: "26M Achievement Boy", price: "£3.49", description: "Celebrate their 26.2 mile running achievement - add a photo, the event name, date and finish time.", categories: ["running"], preview: "26mboy-photo-preview.png", full: "26mboy-photo.png",
    photo: { left: 909.6, top: 331.3, width: 408.1, height: 385.4 },
    extraFields: [
      { key: "event", label: "Event", left: 866, top: 627, fontSize: 18, color: "#F7CD4E", maxChars: 20 },
      { key: "date", label: "Date", left: 861, top: 678, fontSize: 18, color: "#F7CD4E", maxChars: 20 },
      { key: "finishTime", label: "Time", left: 900, top: 732, fontSize: 18, color: "#F7CD4E", maxChars: 12 }
    ] },
  "5kgirl-photo": { title: "5K Achievement Girl", price: "£3.49", description: "Celebrate their 5K running achievement - add a photo, the event name, date and finish time.", categories: ["running"], preview: "5kgirl-photo-preview.png", full: "5kgirl-photo.png",
    photo: { left: 909.6, top: 331.3, width: 408.1, height: 385.4 },
    extraFields: [
      { key: "event", label: "Event", left: 870, top: 603, fontSize: 18, color: "#8B1E5C", maxChars: 20 },
      { key: "date", label: "Date", left: 861, top: 648, fontSize: 18, color: "#8B1E5C", maxChars: 20 },
      { key: "finishTime", label: "Time", left: 912, top: 694, fontSize: 18, color: "#8B1E5C", maxChars: 12 }
    ] },
  "10kgirl-photo": { title: "10K Achievement Girl", price: "£3.49", description: "Celebrate their 10K running achievement - add a photo, the event name, date and finish time.", categories: ["running"], preview: "10kgirl-photo-preview.png", full: "10kgirl-photo.png",
    photo: { left: 909.6, top: 331.3, width: 408.1, height: 385.4 },
    extraFields: [
      { key: "event", label: "Event", left: 870, top: 603, fontSize: 18, color: "#8B1E5C", maxChars: 20 },
      { key: "date", label: "Date", left: 861, top: 648, fontSize: 18, color: "#8B1E5C", maxChars: 20 },
      { key: "finishTime", label: "Time", left: 912, top: 694, fontSize: 18, color: "#8B1E5C", maxChars: 12 }
    ] },
  "26mgirl-photo": { title: "26M Achievement Girl", price: "£3.49", description: "Celebrate their 26.2 mile running achievement - add a photo, the event name, date and finish time.", categories: ["running"], preview: "26mgirl-photo-preview.png", full: "26mgirl-photo.png",
    photo: { left: 909.6, top: 331.3, width: 408.1, height: 385.4 },
    extraFields: [
      { key: "event", label: "Event", left: 870, top: 599, fontSize: 18, color: "#8B1E5C", maxChars: 20 },
      { key: "date", label: "Date", left: 860, top: 644, fontSize: 18, color: "#8B1E5C", maxChars: 20 },
      { key: "finishTime", label: "Time", left: 912, top: 690, fontSize: 18, color: "#8B1E5C", maxChars: 12 }
    ] },

  
};


