// Shared category tree — used by both shop-cards.html (via cards-data.js)
// and shop-prints.html (via prints-data.js). Kept in its own file so a
// change here (e.g. adding a new team or league) applies to cards and
// prints alike, instead of two copies drifting apart.
//
// Load this BEFORE cards-data.js / prints-data.js in any page that needs
// it — those files (and the shop pages' own inline scripts) reference the
// CATEGORIES global defined here.

const CATEGORIES = [
  ["all", "All Cards"],
  ["music", "Music"],
  ["b&w", "Black & White"],
  ["photo-upload", "Photo Upload Cards"],
  ["birthdays", "Birthday Cards", [
    ["mum", "Mum"],
    ["dad", "Dad"],
    ["nan", "Nan"],
    ["grandad", "Grandad"],
    ["childrens", "Kids"],
  ]],
  ["newbaby", "New Baby"],
  ["thank-you", "Thank You! Cards"],
  ["weddings-engagements", "Wedding & Engagement Cards"],
  ["home", "New Home Cards"],
  ["school-cards", "School Cards"],
  ["work-related", "Work Related Cards"],
  ["achievements", "Personal Achievement Cards"],
  ["tv-movies", "TV / Movie Cards"],
  ["mothersday-fathersday", "Mothers & Fathers Day Cards "],
  ["valentines", "Valentines"],
  ["christmas", "Christmas Cards"],
  ["sports", "Sports", [
    ["football", "Football", [
      ["premiership", "Premiership", [
        ["arsenal", "Arsenal"],
        ["aston-villa", "Aston Villa"],
        ["bournemouth", "Bournemouth"],
        ["brentford", "Brentford"],
        ["brighton", "Brighton"],
        ["chelsea", "Chelsea"],
        ["coventry", "Coventry City"],
        ["crystal-palace", "Crystal Palace"],
        ["everton", "Everton"],
        ["fulham", "Fulham"],
        ["hull", "Hull City"],
        ["ipswich", "Ipswich Town"],
        ["leeds", "Leeds United"],
        ["liverpool", "Liverpool"],
        ["man-city", "Manchester City"],
        ["man-utd", "Manchester United"],
        ["newcastle", "Newcastle United"],
        ["forest", "Nottingham Forest"],
        ["sunderland", "Sunderland"],
        ["tottenham", "Tottenham"],
      ]],
      ["championship", "Championship", [
        ["birmingham", "Birmingham City"],
        ["blackburn", "Blackburn Rovers"],
        ["bolton", "Bolton Wanderers"],
        ["bristol-city", "Bristol City"],
        ["burnley", "Burnley"],
        ["cardiff", "Cardiff City"],
        ["charlton", "Charlton Athletic"],
        ["derby", "Derby County"],
        ["lincoln", "Lincoln City"],
        ["middlesbrough", "Middlesbrough"],
        ["millwall", "Millwall"],
        ["norwich", "Norwich City"],
        ["portsmouth", "Portsmouth"],
        ["preston", "Preston North End"],
        ["qpr", "Queens Park Rangers"],
        ["sheffield-utd", "Sheffield United"],
        ["southampton", "Southampton"],
        ["stoke", "Stoke City"],
        ["swansea", "Swansea City"],
        ["watford", "Watford"],
        ["west-brom", "West Bromwich Albion"],
        ["west-ham", "West Ham"],
        ["wolves", "Wolverhampton Wanderers"],
        ["wrexham", "Wrexham"],
      ]],
      ["league-1", "League 1", [
        ["afc-wimbledon", "AFC Wimbledon"],
        ["barnsley", "Barnsley"],
        ["blackpool", "Blackpool"],
        ["bradford", "Bradford City"],
        ["bromley", "Bromley"],
        ["burton", "Burton Albion"],
        ["cambridge", "Cambridge United"],
        ["doncaster", "Doncaster Rovers"],
        ["huddersfield", "Huddersfield Town"],
        ["leicester", "Leicester City"],
        ["leyton-orient", "Leyton Orient"],
        ["luton", "Luton Town"],
        ["mansfield", "Mansfield Town"],
        ["mk-dons", "MK Dons"],
        ["notts-county", "Notts County"],
        ["oxford", "Oxford United"],
        ["peterborough", "Peterborough United"],
        ["plymouth", "Plymouth Argyle"],
        ["reading", "Reading"],
        ["sheffield-wed", "Sheffield Wednesday"],
        ["stevenage", "Stevenage"],
        ["stockport", "Stockport County"],
        ["wigan", "Wigan Athletic"],
        ["wycombe", "Wycombe Wanderers"],
      ]],
      ["league-2", "League 2", [
        ["accrington", "Accrington Stanley"],
        ["barnet", "Barnet"],
        ["bristol-rovers", "Bristol Rovers"],
        ["cheltenham", "Cheltenham Town"],
        ["chesterfield", "Chesterfield"],
        ["colchester", "Colchester United"],
        ["crawley", "Crawley Town"],
        ["crewe", "Crewe Alexandra"],
        ["exeter", "Exeter City"],
        ["fleetwood", "Fleetwood Town"],
        ["gillingham", "Gillingham"],
        ["grimsby", "Grimsby Town"],
        ["newport", "Newport County"],
        ["northampton", "Northampton Town"],
        ["oldham", "Oldham Athletic"],
        ["port-vale", "Port Vale"],
        ["rochdale", "Rochdale"],
        ["rotherham", "Rotherham United"],
        ["salford", "Salford City"],
        ["shrewsbury", "Shrewsbury Town"],
        ["swindon", "Swindon Town"],
        ["tranmere", "Tranmere Rovers"],
        ["walsall", "Walsall"],
        ["york", "York City"],
      ]],
      ["wsl", "WSL / WSL2", [
        ["arsenal", "Arsenal"],
        ["aston-villaw", "Aston Villa"],
        ["birminghamw", "Birmingham City"],
        ["brighton", "Brighton"],
        ["bristol-cityw", "Bristol City"],
        ["burnleyw", "Burnley"],
        ["charltonw", "Charlton Athletic"],
        ["chelseaw", "Chelsea"],
        ["crystal-palacew", "Crystal Palace"],
        ["durham", "Durham"],
        ["evertonw", "Everton"],
        ["ipswichw", "Ipswich Town"],
        ["leicesterw", "Leicester City"],
        ["liverpool", "Liverpool"],
        ["london-city", "London City Lionesses"],
        ["man-cityw", "Manchester City"],
        ["man-utdw", "Manchester United"],
        ["newcastlew", "Newcastle United"],
        ["forestw", "Nottingham Forest"],
        ["sheffield-utdw", "Sheffield United"],
        ["southamptonw", "Southampton"],
        ["sunderlandw", "Sunderland"],
        ["tottenham", "Tottenham"],
        ["watfordw", "Watford"],
        ["westhamw", "West Ham"],
        ["wolvesw", "Wolverhampton Wanderers"],
      ]],
    ]],
    ["golf", "Golf"],
    ["cricket", "Cricket"],
    ["formula1", "Formula 1"],
    ["rugby", "Rugby"],
    ["netball", "Netball"],
    ["darts", "Darts"],
    ["horseracing", "Horse Racing"],
  ]],

];
